### ISSUE TITLE
mmt create should print pipeline errors directly

### ISSUE THREAD

**Issue by cidermole** [ModernMT/MMT#124]
I ran into this with the Czech language (which was incorrectly marked 'cz' - see #125).
The only error indication is that Corpora preprocessing "failed with exit code 1".

```
(mmt)dmadl@sif:/home/shared/mmt/testing/MMT$ nice ./mmt create -e wmt-bench-cs-en cs en /fs/lofn0/mmt
/D5.1-FirstEvalPlan-Corpora-Raw/wmt-bench-cs-en

=========== TRAINING STARTED ===========

ENGINE:  wmt-bench-cs-en
BILINGUAL CORPORA: 4 documents
MONOLINGUAL CORPORA: 8 documents
LANGS:   cs > en

INFO: (1 of 6) TMs clean-up...                                         DONE (in 137s)
INFO: (2 of 6) Corpora preprocessing...                                DONE (in 0s)
2016-05-12 11:25:17,347 [ERROR] - Command 'java -cp /mnt/lofn0/mmt/MMT/build/mmt-0.12.jar -Dmmt.home=
/mnt/lofn0/mmt/MMT -Djava.library.path=/mnt/lofn0/mmt/MMT/lib eu.modernmt.cli.TrainingPipelineMain -s
 cs -t en --output /mnt/lofn0/mmt/MMT/runtime/wmt-bench-cs-en/training/tmp/preprocessed --input /mnt/
lofn0/mmt/MMT/runtime/wmt-bench-cs-en/training/tmp/clean_tms --dev /mnt/lofn0/mmt/MMT/engines/wmt-ben
ch-cs-en/data/dev --test /mnt/lofn0/mmt/MMT/engines/wmt-bench-cs-en/data/test' failed with exit code 
1
Traceback (most recent call last):
  File "/mnt/lofn0/mmt/MMT/scripts/engine.py", line 280, in build
    (self._engine.data_path if split_trainingset else None)
  File "/mnt/lofn0/mmt/MMT/scripts/mt/processing.py", line 61, in process
    shell.execute(command, stdin=shell.DEVNULL, stdout=shell.DEVNULL, stderr=shell.DEVNULL)
  File "/mnt/lofn0/mmt/MMT/scripts/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command 'java -cp /mnt/lofn0/mmt/MMT/build/mmt-0.12.jar -Dmmt.home=/mnt/lofn0/mmt/MMT -Dj
ava.library.path=/mnt/lofn0/mmt/MMT/lib eu.modernmt.cli.TrainingPipelineMain -s cs -t en --output /mn
t/lofn0/mmt/MMT/runtime/wmt-bench-cs-en/training/tmp/preprocessed --input /mnt/lofn0/mmt/MMT/runtime/
wmt-bench-cs-en/training/tmp/clean_tms --dev /mnt/lofn0/mmt/MMT/engines/wmt-bench-cs-en/data/dev --te
st /mnt/lofn0/mmt/MMT/engines/wmt-bench-cs-en/data/test' failed with exit code 1
Traceback (most recent call last):
  File "./mmt", line 527, in <module>
    main()
  File "./mmt", line 495, in main
    main_create(argv[1:])
  File "./mmt", line 478, in main_create
    debug=args.debug, steps=args.training_steps, split_trainingset=args.split_corpora)
  File "/mnt/lofn0/mmt/MMT/scripts/engine.py", line 280, in build
    (self._engine.data_path if split_trainingset else None)
  File "/mnt/lofn0/mmt/MMT/scripts/mt/processing.py", line 61, in process
    shell.execute(command, stdin=shell.DEVNULL, stdout=shell.DEVNULL, stderr=shell.DEVNULL)
  File "/mnt/lofn0/mmt/MMT/scripts/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
scripts.libs.shell.ShellError: Command 'java -cp /mnt/lofn0/mmt/MMT/build/mmt-0.12.jar -Dmmt.home=/mn
t/lofn0/mmt/MMT -Djava.library.path=/mnt/lofn0/mmt/MMT/lib eu.modernmt.cli.TrainingPipelineMain -s cs
 -t en --output /mnt/lofn0/mmt/MMT/runtime/wmt-bench-cs-en/training/tmp/preprocessed --input /mnt/lof
n0/mmt/MMT/runtime/wmt-bench-cs-en/training/tmp/clean_tms --dev /mnt/lofn0/mmt/MMT/engines/wmt-bench-
cs-en/data/dev --test /mnt/lofn0/mmt/MMT/engines/wmt-bench-cs-en/data/test' failed with exit code 1
```

The error message is far from informative: there is no indication of the failure that happened during the step. You have to manually run the command printed, for which you first have to re-run with `--debug` so the temp files used in the command are available. Only then do you get to the real cause:

```
$ ./mmt create --debug -e wmt-bench-cs-en cs en /fs/l
ofn0/mmt/D5.1-FirstEvalPlan-Corpora-Raw/wmt-bench-cs-en
[...]
$ java -cp /mnt/lofn0/mmt/MMT/build/mmt-0.12.jar -Dmmt.home=/mnt/lofn0/mmt/MMT -Djava.library.path=/mnt/lofn0/mmt/MMT/lib eu.modernmt.cli.TrainingPipelineMain -s cs -t en --output /mnt/lofn0/mmt/MMT/runtime/wmt-bench-cs-en/training/tmp/preprocessed --input /mnt/lofn0/mmt/MMT/runtime/wmt-bench-cs-en/training/tmp/clean_tms --dev /mnt/lofn0/mmt/MMT/engines/wmt-bench-cs-en/data/dev --test /mnt/lofn0/mmt/MMT/engines/wmt-bench-cs-en/data/test

Exception in thread "main" java.lang.IllegalArgumentException: Unsupported language: cs
        at eu.modernmt.processing.tokenizer.Tokenizers.forLanguage(Tokenizers.java:133)
        at eu.modernmt.processing.Preprocessor.getPipeline(Preprocessor.java:38)
        at eu.modernmt.engine.training.TrainingPipeline.process(TrainingPipeline.java:104)
        at eu.modernmt.cli.TrainingPipelineMain.main(TrainingPipelineMain.java:100)
```

We should have at least the stacktrace with "Unsupported language: cs" if the regular training fails.

As a bonus, it would be nice if there could be some pipeline sanity checks if the training can be done with the given configuration.

**Comment by davidecaroselli** [comment]
Starting from commit 001b7b83b71ee2ad0d404f6f7264b822dbc019d5 all training output is available in the log file `runtime/<engine>/logs/training.log` including pipeline errors.
