### ISSUE TITLE
tuning failure with very large system (java.lang.NullPointerException in node.log)

### ISSUE THREAD

**Issue by cattoni** [ModernMT/MMT#126]
Given a very large system (cfr. system "NEWstep_05b" in [1], size of its engine/model dir is 49GB), its tuning (with "mmt tune" on dev2) always fails during step 1 with  the following info:

* runtime/NEWstep_05b/logs/node.log:
2016-05-13 10:19:59,161 [qtp231191650-122] DEBUG rest.RESTServer$Router - Executing REST action Translate
2016-05-13 10:19:59,162 [qtp231191650-122] ERROR translation.Translate - Unexpected error while executing action Translate
java.lang.NullPointerException
        at eu.modernmt.core.cluster.ClusterNode.submit(ClusterNode.java:204)
        at eu.modernmt.core.facade.DecoderFacade.translate(DecoderFacade.java:105)
        at eu.modernmt.core.facade.DecoderFacade.translate(DecoderFacade.java:80)
        at eu.modernmt.rest.actions.translation.Translate.execute(Translate.java:40)
        at eu.modernmt.rest.actions.translation.Translate.execute(Translate.java:21)

* runtime/NEWstep_05b/logs/mert.log:
Traceback (most recent call last):
  File "/home/ubuntu/ModernMT/scripts/mertinterface.py", line 189, in <module> translator.run()
  File "/home/ubuntu/ModernMT/scripts/mertinterface.py", line 100, in run self._wait_for_restart()
  File "/home/ubuntu/ModernMT/scripts/mertinterface.py", line 90, in _wait_for_restart raise Exception('Server unavailable - Too many failed attempts')
Exception: Server unavailable - Too many failed attempts
Exit code: 1
The decoder died. CONFIG WAS -weight-overwrite 'PhrasePenalty0= -0.165778 MuxLM= 0.030032 PT0= 0.000897 0.016387 0.102472 0.031115 0.016087 WordPenalty0= -0.124695 Distortion0= 0.005181 DM0= 0.028131 0.025469 0.022996 0.033506 0.044054 0.010615 0.163308 0.179277'

* ls -1 runtime/NEWstep_05b/tmp/tuning/mert/
features.list
run1.dense
run1.moses.ini
run1.out   (empty)

Please note that:
* "mmt evaluate" of the same dev2 file is performed successfully;
* using "$MMT_HOME/extras/translate" to translate the same dev2 file (even with 100 Nbest) is performed successfully too.

[1] https://docs.google.com/spreadsheets/d/19YI2zSm8ZaomYtfIfRpepIPiKMcBaLbqu0vrccPhqR4/edit#gid=0

**Comment by cattoni** [comment]
Found the origin of the problem.

The method $MMT_HOME/scripts/mertinterface.py:_wait_for_restart() (line 80) basically implements a timeout of 5 minutes (60 cycles of 5 secs). Since the engines takes ~11 minutes to start, at the first iteration when the engine is started, the method fails and returns
``
 raise Exception('Server unavailable - Too many failed attempts')
```

@davidecaroselli: in order to fix temporarily the problem, I have now increased the timeout to 20 minutes (40 cycles of 30 secs), but a more general solution is needed. Nicola suggested an interesting way: the timeout is not fixed but it is estimated according to the size of the files
  engines/NEWstep_05b_TED/models/phrase_tables/model.align.(bwd|fwd)
Small files => low timeout, Huge files => high timeout

**Comment by davidecaroselli** [comment]
Bug solved by commit https://github.com/ModernMT/MMT/commit/3aaffd07a9a4c23deb75b564e2a9ee54e088110f.

**Timeout is no longer needed**, in fact new version of MMT does not require restart after feature weights change.
