### ISSUE TITLE
lmplz errors never get flushed to training.lm.log

### ISSUE THREAD

**Issue by cidermole** [ModernMT/MMT#138]
So I failed to build an LM, `lmplz` failed:
```
=========== TRAINING STARTED ===========

ENGINE:  uli-clean.2-en-it
BILINGUAL CORPORA: 45 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 6) TMs clean-up...                                         DONE (in 18s)
INFO: (2 of 6) Corpora preprocessing...                                DONE (in 65s)
INFO: (3 of 6) Context Analyzer training...                            DONE (in 31s)
INFO: (4 of 6) Language Model training...                              DONE (in 334s)
ERROR Unexpected exception:
        Command '/raid0/dmadl/mmt/testing/MMT/opt/bin/kenlm-stable/bin/lmplz --discount_fallback -o 5 -S 1% -T /raid0/dmadl/mmt/testing/MMT/runtime/uli-clean.2-en-it/tmp/training/lm/2.alm' failed with exit code -6
Traceback (most recent call last):
  File "./mmt", line 528, in <module>
    main()
  File "./mmt", line 491, in main
    main_create(args)
  File "./mmt", line 468, in main_create
    debug=args.debug, steps=args.training_steps, split_trainingset=args.split_corpora)
  File "/raid0/dmadl/mmt/testing/MMT/scripts/engine.py", line 145, in build
    self._engine.lm.train(processed_bicorpora + processed_mocorpora, target_lang, working_dir, log_file)
  File "/raid0/dmadl/mmt/testing/MMT/scripts/mt/lm.py", line 225, in train
    adaptive_lm.train([corpus], lang, os.path.join(working_dir, corpus.name + '.alm'))
  File "/raid0/dmadl/mmt/testing/MMT/scripts/mt/lm.py", line 89, in train
    shell.execute(arpa_command, stdin=stdin, stdout=stdout, stderr=log)
  File "/raid0/dmadl/mmt/testing/MMT/scripts/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
scripts.libs.shell.ShellError: Command '/raid0/dmadl/mmt/testing/MMT/opt/bin/kenlm-stable/bin/lmplz --discount_fallback -o 5 -S 1% -T /raid0/dmadl/mmt/testing/MMT/runtime/uli-clean.2-en-it/tmp/training/lm/2.alm' failed with exit code -6
```

But `runtime/uli-clean.2-en-it/logs/training.lm.log` is empty :(

The logs seem to go to a temp folder which is then emptied, see `engine.py`:142:

```
                with cmdlogger.step('Language Model training') as _:
                    working_dir = self._get_tempdir('lm')
                    log_file = self._engine.get_logfile('training.lm')
                    self._engine.lm.train(processed_bicorpora + processed_mocorpora, target_lang, working_dir, log_file)
```

What's the purpose of `logs/training.lm.log`, and shouldn't LM logs go there? Were they too verbose for IRSTLM?

**Comment by davidecaroselli** [comment]
LM logs **must** go there, in `logs/training.lm.log`. Probably the lmplz binary is not invoked in the correct way. Do you think you can fix this issue?

**Comment by davidecaroselli** [comment]
KenLM training output is now piped into `logs/training.lm.log` file.
