### ISSUE TITLE
openSession() fails without a context

### ISSUE THREAD

**Issue by cidermole** [ModernMT/MMT#142]
In tuning with a specific dataset, mert crashed:

```
INFO: (3 of 4) Tuning...                                               DONE (in 352s)
ERROR Unexpected exception:
        Command '/raid0/dmadl/mmt/testing/MMT/opt/bin/moses-mmt-dev_2c29__c231/scripts/mert-moses.pl /raid0/dmadl/mmt/testing/MMT/runtime/euro-senttype-en-de/tmp/tuning/corpus.en /raid0/dmadl/mmt/testing/MMT/runtime/euro-senttype-en-de/tmp/tuning/corpus.de /raid0/dmadl/mmt/testing/MMT/scripts/mertinterface.py /tmp/tmpaY_Jvp --threads 32 --mertdir /raid0/dmadl/mmt/testing/MMT/opt/bin/moses-mmt-dev_2c29__c231/bin --mertargs '--binary --sctype BLEU' --working-dir /raid0/dmadl/mmt/testing/MMT/runtime/euro-senttype-en-de/tmp/tuning/mert --nbest 100 --decoder-flags "--port 8045" --nonorm --closest --no-filter-phrase-table' failed with exit code 2
[...]
```

`mertinterface.py` died as follows:
```
Exception: HTTP request failed with code 500: http://localhost:8045/translate?q=.%0A&processing=0&nbest=100&session=59
Exit code: 1
```

`node.log` reveals:

```
eu.modernmt.core.facade.error.TranslationException: Unexpected error while translating
        at eu.modernmt.core.facade.DecoderFacade.translate(DecoderFacade.java:114)
[...]
Caused by: java.lang.NullPointerException
        at eu.modernmt.decoder.moses.MosesDecoder.openSession(MosesDecoder.java:81)
        at eu.modernmt.core.facade.operations.TranslateOperation.call(TranslateOperation.java:68)
        at eu.modernmt.core.facade.operations.TranslateOperation.call(TranslateOperation.java:19)
        at eu.modernmt.core.cluster.executor.ExecutorDaemon$Worker.run(ExecutorDaemon.java:108)
```

MMT 0dcf170fa1fe6e8e4fa97c77b29b4f1d231a1d91

The `ContextXObject` seems to get a null value.

Session ID 59 had an empty context:
```
2016-05-31 12:07:16,161 [qtp2052814491-161] INFO  rest.RESTServer$Router - REST Request (1c497cb7-e3c3-4506-97a5-062c3aefeb84): GET /context?local_file=%2Ffs%2Flofn0%2Fmmt%2FD5.1-FirstEvalPlan-Corpora-Dev%2Feuro-senttype-en-de%2Fsyn-68be4bc1f54801ba.en
2016-05-31 12:07:16,161 [qtp2052814491-161] DEBUG rest.RESTServer$Router - Executing REST action GetContext
2016-05-31 12:07:16,163 [qtp2052814491-161] INFO  rest.RESTServer$Router - REST Response (1c497cb7-e3c3-4506-97a5-062c3aefeb84): 200 []
```

Admittedly, the specific dev set file `syn-68be4bc1f54801ba.en` is slightly anomalous with two literal dots (stopwords in CA?):

```
.
.
```

I know it's an unlikely tuning scenario, but could occur for a user in translation, I believe. If the CA does not guarantee to give a non-empty result (maybe also in the case of a single unknown word?), then this should be a bug, right?

**Comment by davidecaroselli** [comment]
This is 100% a bug, no doubts! Thanks David.
