### ISSUE TITLE
IOError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by kmlx** [ModernMT/MMT#152]
Hi,

I was playing around with MMT and this happened:

```
 ./mmt create en es ../traindata/

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 6 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > es

INFO: (1 of 6) TMs clean-up...                                         DONE (in 175s)
INFO: (2 of 6) Corpora preprocessing...                                DONE (in 1379s)
INFO: (3 of 6) Context Analyzer training...                            DONE (in 99s)
INFO: (4 of 6) Language Model training...                              DONE (in 3037s)
INFO: (5 of 6) Translation Model training...                           DONE (in 21513s)
ERROR Unexpected exception:
	IOError(28, 'No space left on device')
Traceback (most recent call last):
  File "./mmt", line 440, in <module>
    main()
  File "./mmt", line 406, in main
    main_create(args)
  File "./mmt", line 383, in main_create
    debug=args.debug, steps=args.training_steps, split_trainingset=args.split_corpora)
  File "/home/ubuntu/mmt/scripts/engine.py", line 173, in build
    self._engine.pt.train(processed_bicorpora, self._engine.aligner, working_dir, log_file)
  File "/home/ubuntu/mmt/scripts/mt/phrasetable.py", line 157, in train
    bal_file = aligner.align(merged_corpus, langs, self._model, working_dir, log_file)
  File "/home/ubuntu/mmt/scripts/mt/phrasetable.py", line 248, in align
    encoder.encode(bal_file)
  File "/home/ubuntu/mmt/scripts/mt/phrasetable.py", line 279, in encode
    print >> bal, len(t1), ' '.join(t1), '#', ' '.join(["%d" % x for x in a1])
IOError: [Errno 28] No space left on device

ubuntu@ip-172-31-39-101:~/mmt$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             15G   12K   15G   1% /dev
tmpfs           3.0G  348K  3.0G   1% /run
/dev/xvda1      118G   45G   69G  40% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none             15G     0   15G   0% /run/shm
none            100M     0  100M   0% /run/user
```

Could somebody provide some context as to when this error occurs?
As you can see from ```df -h``` there should be enough space.

**Comment by kmlx** [comment]
I've noticed how disk space shrinks during training. While expected, a warning at the start of training would help in avoiding errors popping up after hours of training; the only mention of disk space usage can be found in this file at the very top: https://github.com/ModernMT/MMT/blob/master/INSTALL.md
This disk space warning could be static text at first, and ideally, later on, dynamic based on actual system and training data disk space values. The warning should be similar to the low CPU/Memory warning. 

P.S. This looks and feels like an interesting project. Congrats!

**Comment by davidecaroselli** [comment]
Hi @kmlx 

a dynamic control on the disk space is already present, unfortunately it cannot be 100% precise: it depends on the data format and the specific corpus your using.

I suspect that this check has failed in your case. Can you please report the output of the commands `du -b traindata/`, `tree traindata/` and `df ModernMT`?

Thanks!

**Comment by davidecaroselli** [comment]
Closing for inactivity. If you have new data,  please, reopen this issue.
Thank you.
