### ISSUE TITLE
Docker - Build Release Error

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#190]
When I try to build a docker image for [MMT/docker/release/Dockerfile]

```
docker build -t modernmt/master .
```

I get this error:

```
Step 14 : RUN ./setup.py
 ---> Running in a4ba371b0c16
Installing kafka-0.10.0.1...Traceback (most recent call last):
  File "./setup.py", line 85, in <module>
    install_apache_lib('/kafka/0.10.0.1/kafka_2.11-0.10.0.1.tgz', 'vendor/kafka-0.10.0.1', name='kafka-0.10.0.1')
  File "./setup.py", line 71, in install_apache_lib
    folder = untar(tardest, wdir)
  File "./setup.py", line 47, in untar
    tar = tarfile.open(filename, 'r:gz')
  File "/usr/lib/python2.7/tarfile.py", line 1678, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1730, in gzopen

    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
```

**Comment by ugermann** [comment]
Can't replicate. Try rebuilding with --no-cache
```
docker build -t modernmt/master --no-cache .
```

The binary release crashes, by the way, but I don't think that has any thing to do with Docker, since the build form source works.

**Comment by marcotrombetti** [comment]
Thanks @ugermann that solved the problem.

I removed all my images and docker containers from my machine and I tried to build the 3 dockerfile provided and I got that:

**MMT/docker/release**
```
docker build -t modernmt/master --no-cache .

Need to get 91.1 MB of archives.
After this operation, 386 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  openjdk-8-jre-headless openjdk-8-jre openjdk-8-jdk-headless openjdk-8-jdk
E: There are problems and -y was used without --force-yes
The command '/bin/sh -c apt-get install -y openjdk-8-jdk' returned a non-zero code: 100
```

**MMT/docker/dev/Ubuntu-14.04**
```
docker build -t modernmt/master --no-cache .

Step 5 : RUN apt-get install -y software-properties-common
 ---> Running in 6716d04ded97
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package software-properties-common
The command '/bin/sh -c apt-get install -y software-properties-common' returned a non-zero code: 100
```

**MMT/docker/dev/Ubuntu-16.04**
```
docker build -t modernmt/master --no-cache .

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/linux-atm/libatm1_2.5.1-1.5_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 117 MB in 58s (2008 kB/s)
The command '/bin/sh -c apt-get install -y build-essential cmake git maven libbz2-dev zlib1g-dev' returned a non-zero code: 100
```

**Comment by davidecaroselli** [comment]
@ugermann could you confirm that the bug has been solved please?

**Comment by marcotrombetti** [comment]
@davidecaroselli @ugermann I think we should decide if to fix the docker build or to remove it.

**Comment by davidecaroselli** [comment]
@marcotrombetti @ugermann due to inactivity I'm going to remove docker folder for now, because it still has problems in compiling and it's not up to date with latest releases.

Files will be still available in the Github history of course.

Thank you
Davide.
