### ISSUE TITLE
translation speed issue

### ISSUE THREAD

**Issue by vince62s** [ModernMT/MMT#218]
I am having an issue with translation speed (as already reported before by some others).

I am running the "evaluate" task.
On one server (bi-proc) 24 cores, but only 16 allocated to the MMT vm (ram 74MGB)
GG speed 0,3 sec per sentence
MMT 2 sec 
Both says "parallelism 9.9x

On another one (single proc) but same as above, only 10 cores allocated to the MMT vm (ram 58GB)
GG speed 0,2
MMT 19 sec parallelism 6x

nothing justifies this. what can happen ?
also what triggers the level of parallelism ?

**Comment by mehmedes** [comment]
I have a server with 16 cores and about 100 GB RAM. Why is the translation speed 83 secs per sentence?

```
Translation Speed:
  Google Translate    : 0.19s per sentence (parallelism 9.8x)
  MMT                 : 83.67s per sentence (parallelism 10.0x)
```

I've trained an English->French engine with about 10 GB training data.

**Comment by davidecaroselli** [comment]
Hi @mehmedes 

so, with MMT version 0.14.1 we solved an important problem with speed. If you already have it installed I recommend also to run on your machine:
```
sudo apt-get remove --purge libgoogle-perftools-dev
sudo apt-get autoremove
```

Beside that MMT currently requires a consistent amount of RAM in order to work. This very slow execution could indicate that the process has not enough memory and it's reading directly from disk. Be sure to have only one engine running at time, and also check if on the same machine there are other processes that are consuming RAM.

Just as a reference, our servers are Amazon EC2 r4.4xlarge instances: 16CPUs, 120GB of RAM and SSD disks. Our engines are ~300M words of parallel text and ~2B words of monolingual text. Out of the box we are able to translate in multithread with a translation time of 1.1s per sentence on average. With some configuration tuning we enhanced the translation speed up to 0.6-0.5s per sentence on average without loosing quality.

**Comment by mehmedes** [comment]
During the translation process of the evaluate set, these are my stats:
```
KiB Mem:  13203659+total, 94604088 used, 37432508 free,   205168 buffers
KiB Swap: 13421772+total,    11836 used, 13420588+free. 63741520 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
10116 sariymx   20   0 84.905g 0.054t 0.029t S 685.0 43.8   4332:00 java
    8 root      20   0       0      0      0 S   0.3  0.0   0:42.23 rcu_sched
14598 sariymx   20   0   24952   3120   2572 R   0.3  0.0   0:00.07 top
```

**Comment by mehmedes** [comment]
I've rebooted the server and can no longer start the engine:
```
ERROR Unexpected exception:
        Exception('failed to start node, check log file for more details: /home/sariymx/ModernMT/runtime/enfr/logs/node.log',)
Traceback (most recent call last):
  File "./mmt", line 549, in <module>
    main()
  File "./mmt", line 526, in main
    actions[command](args)
  File "./mmt", line 199, in main_start
    node.wait('JOINED')
  File "/home/sariymx/ModernMT/cli/cluster.py", line 511, in wait
    raise Exception('failed to start node, check log file for more details: ' + self._log_file)
```
The log file says:
```
2017-02-15 04:17:41,262 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
java.lang.UnsatisfiedLinkError: /home/sariymx/ModernMT/build/lib/librocksvb.so: libtcmalloc.so.4: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at eu.modernmt.vocabulary.rocksdb.RocksDBVocabulary.<clinit>(RocksDBVocabulary.java:23)
        at eu.modernmt.engine.Engine.<init>(Engine.java:82)
        at eu.modernmt.engine.Engine.load(Engine.java:68)
        at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:259)
        at eu.modernmt.facade.ModernMT.start(ModernMT.java:45)
        at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:109)
2017-02-15 04:17:41,656 INFO  com.hazelcast.instance.Node [hz.ShutdownThread] [10.95.0.120]:5016 [eu.modernmt] [3.7.5] Running shutdown hook... Current state: ACTIVE
2017-02-15 04:17:41,657 INFO  com.hazelcast.core.LifecycleService [hz.ShutdownThread] [10.95.0.120]:5016 [eu.modernmt] [3.7.5] [10.95.0.120]:5016 is SHUTTING_DOWN
2017-02-15 04:17:41,657 WARN  com.hazelcast.instance.Node [hz.ShutdownThread] [10.95.0.120]:5016 [eu.modernmt] [3.7.5] Terminating forcefully...
2017-02-15 04:17:41,657 INFO  com.hazelcast.instance.Node [hz.ShutdownThread] [10.95.0.120]:5016 [eu.modernmt] [3.7.5] Shutting down connection manager...
```

**Comment by davidecaroselli** [comment]
Hi @mehmedes,

I know it does not seems so, but we're getting closer to the solution ;).
I made you remove `libgoogle-perftools-dev` in order to remove `libtcmalloc.so` that is responsible of random slow-translation issues.

Now, we need to rebuild MMT in order to get rid of `libtcmalloc.so` definitely. From within the ModernMT root folder (where `mmt` script is) run:
```
rm -rf build/*

cd vendor
make clean
make
cd ..

cd src
mvn clean install
cd ...
```

Try now, and let me know if you're now able to run MMT again. I still think that the slow translation is due to lack of RAM, but this should help a bit.

**Comment by mehmedes** [comment]
Thanks! It's working.

**Comment by nicolabertoldi** [comment]
Actually to remove  libtcmalloc.so
you must run 

$> sudo apt-get remove --purge libtcmalloc
$> sudo apt-get autoremove

Nicola
PS: non totally sure about the exact name of the tcmalloc library, better check  with  command
$> sudo apt search libtcmalloc
