### ISSUE TITLE
Error when running setup.py

### ISSUE THREAD

**Issue by mehmedes** [ModernMT/MMT#230]
I dowonloaded the latest build version this morning.
When running the setup.py, the following read error occurs:

```

Traceback (most recent call last):
  File "./setup.py", line 93, in <module>
    install_apache_lib('/kafka/0.10.0.1/kafka_2.11-0.10.0.1.tgz', 'vendor/kafka-0.10.0.1', name='kafka-0.10.0.1')
  File "./setup.py", line 79, in install_apache_lib
    folder = untar(tardest, wdir)
  File "./setup.py", line 55, in untar
    tar = tarfile.open(filename, 'r:gz')
  File "/usr/lib/python2.7/tarfile.py", line 1678, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1730, in gzopen
    raise ReadError("not a gzip file")
```

**Comment by davidecaroselli** [comment]
I have observed this too: not sure if it's a network problem, or similar. by the way, just re-run it and it will eventually download the file correctly.

**Comment by mehmedes** [comment]
ok :D
