### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#241]
Hi Davide,

Hope it's all well with you and sorry to bother you again.

OK, I have set up a Ubuntu server with 32 GB of RAM and 5 TB hard disk and I have gathered some big TMX files to train my model. I came across this error and it seems out of memory error/garbage collection issue, but I am not sure why. MMT usually throws an alert at the very beginning of training if the memory is not enough to handle the files. I didn't see this alert after increasing the RAM.  So, I am not sure what is causing this. Here is the training.log output:

> 2017-04-02 01:41:43,615 [INFO] - Training started: engine=default, bilingual=11, monolingual=0, langpair=en-ar
2017-04-02 01:41:43,616 [INFO] - Training step "TMs clean-up" (1/7) started
2017-04-02 01:41:43,616 [DEBUG] - Shell exec: java -cp /root/ModernMT/build/mmt-0.15.jar -Dmmt.home=/root/ModernMT -Djava.library.path=/root/ModernMT/build/lib eu.modernmt.cli.CleaningPipe$
2017-04-02 01:41:44,048 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the $
Exception in thread "main" java.lang.Error: Unexpected exception
        at eu.modernmt.training.CleaningPipeline.process(CleaningPipeline.java:91)
        at eu.modernmt.facade.TrainingFacade.clean(TrainingFacade.java:64)
        at eu.modernmt.cli.CleaningPipelineMain.main(CleaningPipelineMain.java:69)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:133)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:220)
        at java.io.Writer.write(Writer.java:157)
        at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeAttribute(XMLStreamWriterImpl.java:544)
        at eu.modernmt.xml.DelegatingXMLStreamWriter.writeAttribute(DelegatingXMLStreamWriter.java:84)
        at eu.modernmt.xml.IndentingXMLStreamWriter.writeAttribute(IndentingXMLStreamWriter.java:34)
        at eu.modernmt.model.corpus.impl.tmx.TMXBilingualLineWriter.write(TMXBilingualLineWriter.java:65)
        at eu.modernmt.training.CleaningTask.call(CleaningTask.java:32)
        at eu.modernmt.training.CleaningTask.call(CleaningTask.java:11)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-04-02 01:55:00,542 [INFO] - Training step "TMs clean-up" completed in 13m 16s
2017-04-02 01:55:00,543 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/root/ModernMT/cli/engine.py", line 229, in build
    unprocessed_bicorpora, self._get_tempdir('clean_tms'), log=logger.stream)
  File "/root/ModernMT/cli/mt/processing.py", line 99, in clean
    shell.execute(command, stdout=log, stderr=log)
  File "/root/ModernMT/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command 'java -cp /root/ModernMT/build/mmt-0.15.jar -Dmmt.home=/root/ModernMT -Djava.library.path=/root/ModernMT/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ar --ou$

Thanks in advance for your support.

Mohamed

**Comment by memoday** [comment]
It might be worth-mentioning that if I type this command

`java -XshowSettings:vm`

I get this result:

> VM settings:
>     Max. Heap Size (Estimated): 6.97G
>     Ergonomics Machine Class: server
>     Using VM: OpenJDK 64-Bit Server VM

So, it seems the heap size is OK. I am not sure what is causing such memory leak and what is the solution?

Thanks

**Comment by AndRossi** [comment]
Hi @memoday,
The problem is caused by the dimension of your TMX, that raises issues during the cleaning process; i am solving the problem right now.
We will keep you updated. 
Thanks for your support!

**Comment by AndRossi** [comment]
Hi @memoday, 
I have just pushed in our master branch an update that should fix your problem.

Just update your MMT version executing from your MMT main folder the command:
```
git pull origin master
```
 
After that, go to the source folder and build the code: 
```
cd src
mvn clean install
```

You can now try the MMT create again.
I hope now everything works fine. Let me know! :) 

Andrea

**Comment by memoday** [comment]
Thanks Andrea for your so fast follow-up. I appreciate it. I will test this once I am done with the test training I am doing. What I did yesterday was that: removing all TMX and simply used .en and .ar parallel text and it worked after that. Is this what you mean by 'the dimension of your TMX'? 

Thanks again for your support. I will report back here after testing it.

Have a wonderful day!

Thanks,
Mohamed Zeid

**Comment by AndRossi** [comment]
Hi @mzeidhassan,

The problem was not the combination of tmx files and parallel corpora files: combining tmx and parallel corpora is already supported MMT. In your case, training really big TMX files led the cleaning process to run out of memory. 

With the new fix, the amount of memory allocated for cleaning is increased so the problem should be solved. 

If if it not and you get that memory error again, it means that the cleaning process needs even more memory; in that case I suggest you to just skip the cleaning phase. You can do so by launching the create telling it manually which steps to perform:

```
./mmt create <src_language> <target_language> <your_folder>  -s preprocess context_analyzer aligner tm lm
```

As for the variations of Arabic in the tmx files (AR-SA, AR-AE, AR-JO) don't worry, they are not a problem since MMT recognizes all these variations as Arabic.

I hope everything works fine now. 
I'm closing this issue now, however don't hesitate to re-open it if you have any problems or questions.

Have a nice day!

Andrea

**Comment by mzeidhassan** [comment]
Hi Andrea,

Sorry to reopen this. After about 22 hours, the training failed  after the completion of the 4th phase "Aligner training..."


> =========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 12 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > ar

INFO: (1 of 7) TMs clean-up...                                         DONE (in 4m 10s)
INFO: (2 of 7) Corpora preprocessing...                                DONE (in 30m 21s)
INFO: (3 of 7) Context Analyzer training...                            DONE (in 2m 56s)
INFO: (4 of 7) Aligner training...                                     DONE (in 21h 5m 57s)
ERROR Unexpected exception:
	Command '/root/ModernMT/build/bin/fa_build -s /root/ModernMT/runtime/default/tmp/training/aligner/merge.en -t /root/ModernMT/runtime/default/tmp/training/aligner/merge.ar -m /root/ModernMT/engines/default/models/align -I 4' failed with exit code -9
Traceback (most recent call last):
  File "./mmt", line 570, in <module>
    main()
  File "./mmt", line 547, in main
    actions[command](args)
  File "./mmt", line 373, in main_create
    debug=args.debug, steps=args.training_steps, split_trainingset=args.split_corpora)
  File "/root/ModernMT/cli/engine.py", line 258, in build
    self._engine.aligner.build(cleaned_bicorpora, working_dir, log=logger.stream)
  File "/root/ModernMT/cli/mt/phrasetable.py", line 59, in build
    shell.execute(command, stdout=log, stderr=log)
  File "/root/ModernMT/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
cli.libs.shell.ShellError: Command '/root/ModernMT/build/bin/fa_build -s /root/ModernMT/runtime/default/tmp/training/aligner/merge.en -t /root/ModernMT/runtime/default/tmp/training/aligner/merge.ar -m /root/ModernMT/engines/default/models/align -I 4' failed with exit code -9



and here is the training.log output:

`2017-04-03 20:06:05,669 [INFO] - Training step "Corpora preprocessing" completed in 30m 21s
2017-04-03 20:06:05,669 [INFO] - Training step "Context Analyzer training" (3/7) started
2017-04-03 20:06:05,669 [DEBUG] - Shell exec: java -cp /root/ModernMT/build/mmt-0.15.1.jar -Dmmt.home=/root/ModernMT -Djava.library.path=/root/ModernMT/build/lib eu.modernmt.cli.ContextAnalyzerMain -s en -t ar -i /root/ModernMT/engines/default/models/context -c /root/ModernMT/runtime/default/tmp/training/training_corpora
2017-04-03 20:06:06,142 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-04-03 20:06:06,709 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of domain 1
2017-04-03 20:06:07,115 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of domain 2
[main] Bulk insert of domain 3
2017-04-03 20:06:08,650 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of domain 4
2017-04-03 20:06:08,680 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of domain 5
2017-04-03 20:06:09,687 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of domain 6
2017-04-03 20:06:09,704 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of domain 7
2017-04-03 20:06:13,696 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of domain 8
2017-04-03 20:07:35,062 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of domain 9
2017-04-03 20:08:15,552 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of domain 10
2017-04-03 20:08:15,989 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of domain 11
2017-04-03 20:08:16,463 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of domain 12
2017-04-03 20:08:16,463 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Flushing index to disk. Pending updates: 12
2017-04-03 20:08:16,463 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Flushing index to disk. Pending updates: 12
2017-04-03 20:08:16,465 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-1] Indexing bucket 1
2017-04-03 20:08:16,468 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-2] Indexing bucket 2
2017-04-03 20:08:16,468 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-3] Indexing bucket 3
2017-04-03 20:08:16,468 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-4] Indexing bucket 4
2017-04-03 20:08:16,773 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-1] Indexing bucket 5
2017-04-03 20:08:16,825 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-1] Indexing bucket 6
2017-04-03 20:08:16,924 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-2] Indexing bucket 7
2017-04-03 20:08:16,933 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-2] Indexing bucket 8
2017-04-03 20:08:16,970 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-4] Indexing bucket 9

`2017-04-03 20:08:17,216 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-3] Indexing bucket 10
2017-04-03 20:08:17,239 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-1] Indexing bucket 11
2017-04-03 20:08:17,320 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-1] Indexing bucket 12
2017-04-03 20:09:02,580 [INFO] - Training step "Context Analyzer training" completed in 2m 56s
2017-04-03 20:09:02,581 [INFO] - Training step "Aligner training" (4/7) started
2017-04-03 20:09:36,077 [DEBUG] - Shell exec: /root/ModernMT/build/bin/fa_build -s /root/ModernMT/runtime/default/tmp/training/aligner/merge.en -t /root/ModernMT/runtime/default/tmp/training/aligner/merge.ar -m /root/ModernMT/engines/default/models/align -I 4
== Forward model training ==
Initial setup... DONE in 1090.96s
Iteration 1:
        Computing alignments... DONE in 1824.09s
        Optimizing diagonal tension... DONE in 0.474769s
        Normalizing translation table... 2017-04-04 17:15:02,182 [INFO] - Training step "Aligner training" completed in 21h 5m 57s
2017-04-04 17:15:04,253 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/root/ModernMT/cli/engine.py", line 258, in build
    self._engine.aligner.build(cleaned_bicorpora, working_dir, log=logger.stream)
  File "/root/ModernMT/cli/mt/phrasetable.py", line 59, in build
    shell.execute(command, stdout=log, stderr=log)
  File "/root/ModernMT/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command '/root/ModernMT/build/bin/fa_build -s /root/ModernMT/runtime/default/tmp/training/aligner/merge.en -t /root/ModernMT/runtime/default/tmp/training/aligner/merge.ar -m /root/ModernMT/engines/default/models/align -I 4' failed with exit code -9


Any idea?

thanks,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan,
something went wrong during the Aligner training (such a long time for that phase is definitely not normal!).

Could you please send us the files you are trying to use for training? (unless they are private, of course). This way we can launch training on our machines and check what's going wrong. 

Thanks for your patience!
Andrea

**Comment by mzeidhassan** [comment]
Hi Andrea,

They are private, so I cannot share them, but one of the files, the biggest indeed, is the UN EN_AR corproa. 

Do you think it makes more sense to start training with this file first and see how it goes, then keep adding the other files one by one? Would that be a better approach for now? 

If yes, can you please let me know the command to add tmx files to an already-built engine?

Thanks,
Mohamed

**Comment by cattoni** [comment]
Hi @mzeidhassan 

Could you check how free space is left on the hard disk after the error? 
In the first post of this issue you mentioned to have '5 GB hard disk' which could be not sufficient for large data training.

**Comment by mzeidhassan** [comment]
Hi cattoni,

Sorry, I meant 5 TB. Here is the current status anyway


 

> System information as of Thu Apr  6 03:44:04 MDT 2017
> 
>   System load:  0.08             Processes:             252
>   Usage of /:   0.8% of 4.50TB   Users logged in:       1
>   Memory usage: 6%                 Swap usage:   30%              
>

**Comment by AndRossi** [comment]
Hi @mzeidhassan,

Yes, you can try using the biggest file in order to check if it is the one that raises the issue.
If it doesn't, you can add TMXs one by one with this command:

```
./mmt import -x <path to your TMX>
```
Let me know if the issue is raised again.

Thanks for your support!

Andrea

**Comment by mzeidhassan** [comment]
Hi Andrea,

I am doing it right now and I will report the outcome here once it's done.

Thanks for your support!

Mohamed

**Comment by mzeidhassan** [comment]
Hi Andrea,
If failed again with UN corpora only. FYI, the EN file is about 3.2 GB and the Arabic file is about 4 GB. Can MMT handle such big files? Should I split them in smaller files? If yes, what is the ideal file size?

Thanks,
Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan , 

We believe the memory problem during Aligner Training is raised by the fact that your machine has the swap option enabled.
Unfortunately, splitting the file in smaller chunks cannot solve the problem because in that training phase all the files in the corpus are concatenated in a single one, so your smaller chunks would be just merged again.

If you can give us a link to the UN corpus we can try launch it on our machines and check if our guess about the swap option is right and fix it.

Thanks again for your patience and support!

Andrea

**Comment by mzeidhassan** [comment]
Hi Andrea,

You can download it from here. https://conferences.unite.un.org/UNCorpus

Click on Downoload and enter the info and you will get right away after that the links. You need to download the one for EN-AR. I downloaded the bi-text version. 

Please let me know how it goes. I will be waiting for your feedback!

On a different note, should I disable the swap option? 

Thanks again! 

Mohamed

**Comment by AndRossi** [comment]
Hi @mzeidhassan 

We checked the memory usage during the training on the UN corpus.
The used RAM spikes over 43 GB - which exceeds by far the 32 GB of your machine.
This is the reason why your machine suddenly crashes. 

As for the swap option, if you are working on a server (as I understand) i suggest you to disable it.
Swap means transferring parts of your RAM to your secondary memory. 
However, since in servers most of the data you store in RAM are necessary for the server work, this does not solve your memory issue. Moreover, swapping chunks of memory leads to lots of reads and writes from secondary memory. 
Hence training times get unbearably long (your 21 hours), until the process reach the swap limit and crashes.

In order to avoid the memory overloading issue you can either switch to a machine with more memory or use just a portion of the UN corpus.

I saw that the -en file in the UN corpus contains more than 440’000’000 words: for instance, you could use just half of them, accordingly cutting the -ar file as well, and see if your machine manages to do the job (assuming that your private corpora sizes are not relevant in comparison to the UN corpus size). Take into account that MMT has proved to reach great precision with corpora of that size.

**Comment by mzeidhassan** [comment]
Thanks Andrea for your great explanation and for taking the time to investigate the issue. This is a home-based server I use mainly for testing and experimenting. I can increase the RAM to 48 "adding another 16 GB RAM" and see how it goes. 

Thanks again for your continuous support.
