### ISSUE TITLE
librocksdb.so.4.13 causing java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by yonkornilov** [ModernMT/MMT#260]
I'm using the docker image. Freshly pulled. When I try to create the example engine: `./mmt create en it examples/data/train/` I get an error in the second stage:
```
INFO: (2 of 7) Corpora pre-processing...                               DONE (in 0s)
ERROR Unexpected exception:
	Command 'java -cp /home/mmtuser/mmt/build/mmt-1.0.2.jar -Dmmt.home=/home/mmtuser/mmt -Djava.library.path=/home/mmtuser/mmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t it -v /home/mmtuser/mmt/engines/default/models/vocabulary --output /home/mmtuser/mmt/runtime/default/tmp/training/preprocessed --input /home/mmtuser/mmt/runtime/default/tmp/training/training_corpora --dev /home/mmtuser/mmt/engines/default/data/dev --test /home/mmtuser/mmt/engines/default/data/test' failed with exit code -6
```
I can try seeing the full Java output by re-running the above command, which yields this output:
```
2017-07-29 11:33:15,028 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-07-29 11:33:15,158 ERROR eu.modernmt.vocabulary.rocksdb.RocksDBVocabulary [main] Unable to load library 'mmt_vocabulary'
java.lang.UnsatisfiedLinkError: /home/mmtuser/mmt/build/lib/libmmt_vocabulary.so: librocksdb.so.4.13: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at eu.modernmt.vocabulary.rocksdb.RocksDBVocabulary.<clinit>(RocksDBVocabulary.java:23)
	at eu.modernmt.training.preprocessing.VocabularyEncoderWriter.<init>(VocabularyEncoderWriter.java:18)
	at eu.modernmt.facade.TrainingFacade.preprocess(TrainingFacade.java:80)
	at eu.modernmt.cli.TrainingPipelineMain.main(TrainingPipelineMain.java:97)
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/mmtuser/mmt/build/lib/libmmt_vocabulary.so: librocksdb.so.4.13: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at eu.modernmt.vocabulary.rocksdb.RocksDBVocabulary.<clinit>(RocksDBVocabulary.java:23)
	at eu.modernmt.training.preprocessing.VocabularyEncoderWriter.<init>(VocabularyEncoderWriter.java:18)
	at eu.modernmt.facade.TrainingFacade.preprocess(TrainingFacade.java:80)
	at eu.modernmt.cli.TrainingPipelineMain.main(TrainingPipelineMain.java:97)
```

Not sure what the issue here is... `-Djava.library.path=/home/mmtuser/mmt/build/lib` implies librocksdb.so.4.13 should be in ~/mmt/build/lib...

`ls ~/mmt/build/lib | grep librocksdb.so.4.13` shows that it is...

**Comment by yonkornilov** [comment]
`ldconfig -v -N | grep rock` doesn't list librocksdb, indicating it's not one of the available libraries.

**Comment by yonkornilov** [comment]
I've manually added /home/mmtuser/mmt/build/lib into ldconfig. Now librocksdb loads, at step 2 the JVM has a runtime error when running librocksdb C-code:

```
# Problematic frame:
# C  [librocksdb.so.4.13+0x1ac5e2]  std::_Hashtable<std::string, std::pair<std::string const, rocksdb::OptionTypeInfo>, std::allocator<std::pair<std::string const, rocksdb::OptionTypeInfo> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_Hashtable<std::pair<std::string const, rocksdb::OptionTypeInfo> const*>(std::pair<std::string const, rocksdb::OptionTypeInfo> const*, std::pair<std::string const, rocksdb::OptionTypeInfo> const*, unsigned long, std::hash<std::string> const&, std::__detail::_Mod_range_hashing const&, std::__detail::_Default_ranged_hash const&, std::equal_to<std::string> const&, std::__detail::_Select1st const&, std::allocator<std::pair<std::string const, rocksdb::OptionTypeInfo> > const&)+0x62
```

**Comment by AndRossi** [comment]
Hello @yonkornilov,

We have tried to perform a fresh image pull and unfortunately we were not able to replicate your issue in our environment yet.

Did you pull the master image with command `docker pull modernmt/master`, and run it with command `docker run -it --publish 8045:8045 modernmt/master bash`?

If so, you should find a more detailed log file in your running image, in path: `/home/mmtuser/mmt/runtime/default/logs/training.log`.
That log file should contain more explicit information on what went wrong with your default machine. 
Could you please send me its content?

(However, as long as you try to use the default en-it engine, you don't have to create it explicitly since it is automatically created at image start. You can directly start it with command:
`./mmt start`. However that should not be the cause of your issue).

Andrea

**Comment by yonkornilov** [comment]
```
2017-07-30 16:24:30,236 [INFO] - Training started: engine=default, bilingual=3, monolingual=0, langpair=en-it
2017-07-30 16:24:30,239 [INFO] - Training step "TMs clean-up" (1/7) started
2017-07-30 16:24:30,239 [DEBUG] - Shell exec: java -Xmx7002m -cp /home/mmtuser/mmt/build/mmt-1.0.2.jar -Dmmt.home=/home/mmtuser/mmt -Djava.library.path=/home/mmtuser/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t it --output /home/mmtuser/mmt/runtime/default/tmp/training/clean_tms --input /home/mmtuser/mmt/examples/data/train
2017-07-30 16:24:30,846 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-07-30 16:24:31,240 [INFO] - Training step "TMs clean-up" completed in 1s
2017-07-30 16:24:31,241 [INFO] - Training step "Corpora pre-processing" (2/7) started
2017-07-30 16:24:31,242 [DEBUG] - Shell exec: java -cp /home/mmtuser/mmt/build/mmt-1.0.2.jar -Dmmt.home=/home/mmtuser/mmt -Djava.library.path=/home/mmtuser/mmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t it -v /home/mmtuser/mmt/engines/default/models/vocabulary --output /home/mmtuser/mmt/runtime/default/tmp/training/preprocessed --input /home/mmtuser/mmt/runtime/default/tmp/training/training_corpora --dev /home/mmtuser/mmt/engines/default/data/dev --test /home/mmtuser/mmt/engines/default/data/test
2017-07-30 16:24:31,826 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fb7cfb465e2, pid=867, tid=0x00007fb825fcc700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b14) (build 1.8.0_111-8u111-b14-3~14.04.1-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librocksdb.so.4.13+0x1ac5e2]  std::_Hashtable<std::string, std::pair<std::string const, rocksdb::OptionTypeInfo>, std::allocator<std::pair<std::string const, rocksdb::OptionTypeInfo> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_Hashtable<std::pair<std::string const, rocksdb::OptionTypeInfo> const*>(std::pair<std::string const, rocksdb::OptionTypeInfo> const*, std::pair<std::string const, rocksdb::OptionTypeInfo> const*, unsigned long, std::hash<std::string> const&, std::__detail::_Mod_range_hashing const&, std::__detail::_Default_ranged_hash const&, std::equal_to<std::string> const&, std::__detail::_Select1st const&, std::allocator<std::pair<std::string const, rocksdb::OptionTypeInfo> > const&)+0x62
#
# Core dump written. Default location: /home/mmtuser/mmt/core or core.867
#
# An error report file with more information is saved as:
# /home/mmtuser/mmt/hs_err_pid867.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
2017-07-30 16:24:32,110 [INFO] - Training step "Corpora pre-processing" completed in 0s
2017-07-30 16:24:32,111 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/mmtuser/mmt/cli/engine.py", line 346, in _build
    delete_on_exit=delete_on_exit)
  File "/home/mmtuser/mmt/cli/engine.py", line 442, in _run_step
    result = step_function(*values, skip=skip, logger=logger, delete_on_exit=delete_on_exit)
  File "/home/mmtuser/mmt/cli/engine.py", line 498, in _step_preprocess
    log=logger.stream)
  File "/home/mmtuser/mmt/cli/mt/processing.py", line 128, in process
    shell.execute(command, stdout=log, stderr=log)
  File "/home/mmtuser/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command 'java -cp /home/mmtuser/mmt/build/mmt-1.0.2.jar -Dmmt.home=/home/mmtuser/mmt -Djava.library.path=/home/mmtuser/mmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t it -v /home/mmtuser/mmt/engines/default/models/vocabulary --output /home/mmtuser/mmt/runtime/default/tmp/training/preprocessed --input /home/mmtuser/mmt/runtime/default/tmp/training/training_corpora --dev /home/mmtuser/mmt/engines/default/data/dev --test /home/mmtuser/mmt/engines/default/data/test' failed with exit code -6
```

**Comment by cattoni** [comment]
Hi @AndRossi 

A very similar error happened to me when trying to run MMT binary release (compiled on Ubuntu) on RedHat7.2.
To fix it, I had to re-compile everything from scratch on RedHat7.2.
However, not sure if this can fit in the docker problem...

Best

   Roldano

**Comment by AndRossi** [comment]
Hi @yonkornilov  

After further investigation, I think your issue is caused by some hardware assumptions made by the librocksdb module. 
As @cattoni said, recompiling the software in your environment should fix it.
To do this, you can follow [our install MMT from sources guide](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source-for-contributors). 
You can install MMT from sources either on your docker image or directly your machine, if its OS is Ubuntu 14.04 or 16.04.

To be sure about the nature of your issue, could you please send me your `/home/mmtuser/mmt/hs_err_pid867.log` file? You can just attach it by dragging and dropping it. 

Thanks for your patience!

Andrea

**Comment by AndRossi** [comment]
Hi @yonkornilov,

I'm closing this issue due to inactivity.
However, for any update or doubt, don't hesitate to reopen it!

Andrea

**Comment by yonkornilov** [comment]
@AndRossi no worries.
