### ISSUE TITLE
Failed to join member to cluster

### ISSUE THREAD

**Issue by rptl** [ModernMT/MMT#264]
Getting Host unreachable message when run start --join-leader

Follower: 192.168.5.100
Leader: 192.168.5.101

.101 is listening on 9092 port and TCP connection is working fine from .100 to .101 (ie: using telnet, nc, etc)

node.log
```
2017-08-16 12:03:25,330 INFO  eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
2017-08-16 12:03:25,903 INFO  com.hazelcast.instance.DefaultAddressPicker [main] [LOCAL] [eu.modernmt] [3.7.5] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [192.168.5.101]
2017-08-16 12:03:25,903 INFO  com.hazelcast.instance.DefaultAddressPicker [main] [LOCAL] [eu.modernmt] [3.7.5] Prefer IPv4 stack is true.
2017-08-16 12:03:25,918 WARN  com.hazelcast.instance.DefaultAddressPicker [main] [LOCAL] [eu.modernmt] [3.7.5] Could not find a matching address to start with! Picking one of non-loopback addresses.
2017-08-16 12:03:25,939 INFO  com.hazelcast.instance.DefaultAddressPicker [main] [LOCAL] [eu.modernmt] [3.7.5] Picked [192.168.5.100]:5016, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5016], bind any local is true
2017-08-16 12:03:25,939 INFO  com.hazelcast.instance.DefaultAddressPicker [main] [LOCAL] [eu.modernmt] [3.7.5] Using public address: [192.168.5.100]:5016
2017-08-16 12:03:25,944 INFO  com.hazelcast.system [main] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] Hazelcast 3.7.5 (20170124 - 111f332) starting at [192.168.5.100]:5016
2017-08-16 12:03:25,944 INFO  com.hazelcast.system [main] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.
2017-08-16 12:03:25,944 INFO  com.hazelcast.system [main] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] Configured Hazelcast Serialization version : 1
2017-08-16 12:03:26,255 INFO  com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator [main] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] Backpressure is disabled
2017-08-16 12:03:26,750 INFO  com.hazelcast.instance.Node [main] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] Creating TcpIpJoiner
2017-08-16 12:03:26,910 INFO  com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl [main] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] Starting 4 partition threads
2017-08-16 12:03:26,912 INFO  com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl [main] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] Starting 3 generic threads (1 dedicated for priority tasks)
2017-08-16 12:03:26,918 INFO  com.hazelcast.core.LifecycleService [main] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] [192.168.5.100]:5016 is STARTING
2017-08-16 12:03:26,919 INFO  com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThreadingModel [main] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads
2017-08-16 12:03:26,974 INFO  com.hazelcast.nio.tcp.InitConnectionTask [hz._hzInstance_1_eu.modernmt.cached.thread-3] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] Connecting to /192.168.5.101:5016, timeout: 0, bind-any: true
2017-08-16 12:03:26,981 INFO  com.hazelcast.nio.tcp.TcpIpConnectionManager [hz._hzInstance_1_eu.modernmt.cached.thread-3] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] Established socket connection between /192.168.5.100:40553 and /192.168.5.101:5016
2017-08-16 12:03:32,980 INFO  com.hazelcast.internal.cluster.ClusterService [hz._hzInstance_1_eu.modernmt.priority-generic-operation.thread-0] [192.168.5.100]:5016 [eu.modernmt] [3.7.5]

Members [2] {
	Member [192.168.5.101]:5016 - 31c6369a-f179-4a7c-a000-6b790c310daf
	Member [192.168.5.100]:5016 - b9b29156-b6c3-422d-88f5-d0d62d63a2a4 this
}

2017-08-16 12:03:38,000 INFO  com.hazelcast.instance.HazelcastInstanceImpl [main] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] HazelcastInstance starting after waiting for cluster size of 2
2017-08-16 12:03:38,001 INFO  com.hazelcast.core.LifecycleService [main] [192.168.5.100]:5016 [eu.modernmt] [3.7.5] [192.168.5.100]:5016 is STARTED
2017-08-16 12:03:38,002 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined the cluster in 12.235s
2017-08-16 12:03:38,003 WARN  eu.modernmt.cluster.ClusterNode [main] Model syncing not supported in this version!
2017-08-16 12:03:38,006 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2017-08-16 12:05:44,227 INFO  eu.modernmt.cluster.ClusterNode [main] Model loaded in 126.221s
2017-08-16 12:05:44,233 INFO  eu.modernmt.cluster.ClusterNode [main] Connecting to dataManager...
2017-08-16 12:06:44,586 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
eu.modernmt.engine.BootstrapException: Unable to connect to DataManager
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:384)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:45)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:182)
Caused by: eu.modernmt.data.HostUnreachableException: **Host unreachable: 192.168.5.101:9092**
	at eu.modernmt.cluster.kafka.KafkaDataManager.connect(KafkaDataManager.java:210)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:368)
	... 2 more
```

**Comment by AndRossi** [comment]
Hello @rptl, 
Unfortunately we were not able to replicate your issue in our environment.   
Reading your log, your engines manage to communicate and form a cluster using port 5016.
On the contrary, as you pointed out, they have trouble with the data communication on port 9092.
  
The fact that only one of these communications fails is very odd, and it hints that the issue might depend on the environment the engines are deployed on - however I'll do my best to assist you.

Are you using the most recent MMT version, and the same MMT version, on the two machines? (this is quite trivial, but it is always worth a check).
Are you using more than one ethernet interface on your machines? If so, it is possible that your .101 machine is listening on a different interface from the one that .100 is trying to reach. 
Another possibility is that some firewall policy interferes with communications towards your .101:9092. 
You may also check if the log file in the leader node shows relevant information on the follower trying to reach it.

Please let me know if this helps.

Andrea

**Comment by rptl** [comment]
Hey @AndRossi 
First on all, thanks for your time to look into it.

Something IMPORTANT, that I did not mention: both servers are running as Linux Containers (lxd) and that can be the issue, since there are some different network types... 
 
1 - There are no fw issues, both servers are in the same subnet and attached to same host. 
Just for references: per logs you can see hazelcast recognizing connection and joining servers.

2- On some attempt I've observed  some "content lenght error" on leader kafka.log, then connection shut down. Will try to reproduce again.

3 - We don't need to leave it opened as an issue. There is no mention on MMT that LXC is not supported. I just wanted to get in touch with you, perhaps you already have faced something similar and had some hints. 
I might want to play around with those things again. I can reopen to give some update when I'll go deeper on it.

Thanks again!

**Comment by AndRossi** [comment]
Hello @rptl,  
thanks for the additional information.
  
I think that the issue might be raised by the LXD networking system, but my knowledge in LXD containers is not deep enough to confirm it.

However, I do have an hint about a possible cause.
I know that, for its networking, LXD uses bridge lxdbr0, that uses IPV6 addresses by default.
It is possible that while your Kafka server listens to port 9092 on your IPV6 address, your Kafka client tries to contact it on an IPV4 address (or vice versa).
We had a similar problem some time ago (but it involved hazelcast, not Kafka).
I really hope this helps!
  
As you proposed I am now closing this issue, but please re-open it or send new comments if you have new information on this. 

Thanks again for your patience.
Have a great day!

Andrea

**Comment by rptl** [comment]
I have found the issue. It's silly, but I had to add host names on /etc/host for both servers (even using only IP address on command line). Probably kafka try to perform some name resolution and crash.

Things that I had to change to run on LXD/LXC containers so far:
- Have to add <installroot>/build/lib on LD Library path - it was dying during training complaining about a .so (I don't recall which one): error msg
ERROR Unexpected exception:
	Command '/opt/ModernMT/build/bin/create_alm -m /opt/ModernMT/engines/engine1/models/decoder/lm/foreground.alm -i /opt/ModernMT/runtime/engin1/tmp/training/lm/alm_train -b 50000000' failed with exit code -6

- added entries for all nodes on /etc/hosts (all servers). ie:
10.1.1.1 mmt1
10.1.1.2 mmt2

So far, so good using LXC. 

Questions: 
What you guys think about add a load balancer to cluster topology? I am thinking  to add it to balance requests among clusters.

**Comment by AndRossi** [comment]
Hi @rptl,

This is great news! I'm glad you found the solution and managed to run MMT on LXC.
The solution is actually very interesting: the same issue might be raised in other environments too, and knowing how to handle it is extremely valuable. 
So thank you for your nice work!

As for the load balancer, the cluster already implements a load balancing system of its own. 
When a request (e.g. a REST API call) arrives to a machine, the task to execute is spread throughout the cluster nodes, and is performed by the least busy node.
A load balancer, however, might be useful because it would provide a unique access point to the cluster (so if a node fails the user won't even notice!).

If you are willing to play with a load balancer I can suggest you [HAProxy](http://www.haproxy.org/).

Thank you again. Have a wonderful day!

Andrea

**Comment by rptl** [comment]
Yep, HAProxy it is. 
Just for reference, I built a container using Alpine+HAproxy  using 9.6M of disk space only. It's working like a champ.
