### ISSUE TITLE
With a killed neural training, engine doesn't start

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#288]
As said in the other discussion, I tried to kill the very long neural training. When I try to start the engine, I got this in the LOG:
`2017-10-20 16:41:19,254 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]`
`eu.modernmt.engine.BootstrapException: Failed to instantiate NMT Decoder`
`	at eu.modernmt.engine.impl.NeuralEngine.<init>(NeuralEngine.java:35)`
`	at eu.modernmt.engine.Engine.load(Engine.java:70)`
`	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:319)`
`	at eu.modernmt.facade.ModernMT.start(ModernMT.java:49)`
`	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:168)`
`Caused by: eu.modernmt.decoder.neural.NeuralDecoderException: Failed to read file model.conf`
`	at eu.modernmt.decoder.neural.NeuralDecoder.<init>(NeuralDecoder.java:45)`
`	at eu.modernmt.engine.impl.NeuralEngine.<init>(NeuralEngine.java:31)`
`	... 4 more`
`Caused by: java.io.FileNotFoundException: /home/lm-dev8/MMT2/ModernMT/engines/ENFR_N/models/decoder/model.conf (No such file or directory)`
`	at java.io.FileInputStream.open0(Native Method)`
`	at java.io.FileInputStream.open(FileInputStream.java:195)`
`	at java.io.FileInputStream.<init>(FileInputStream.java:138)`
`	at java.io.FileReader.<init>(FileReader.java:72)`
`	at eu.modernmt.decoder.neural.ModelConfigFile.load(ModelConfigFile.java:27)`
`	at eu.modernmt.decoder.neural.NeuralDecoder.<init>(NeuralDecoder.java:43)`
`	... 5 more`

**Comment by EtienneAb3d** [comment]
This model.conf file seems very trivial to build manually. This done, I know got this:
`2017-10-20 17:12:37,186 INFO  eu.modernmt.decoder.neural.execution.NativeProcess [Thread-4] (nmmt.NMTDecoder) Loading "en__fr" model from checkpoint... START
2017-10-20 17:12:39,586 INFO  eu.modernmt.decoder.neural.execution.NativeProcess [Thread-4] (nmmt.NMTDecoder) Loading "en__fr" model from checkpoint END 2.40s
2017-10-20 17:12:39,628 ERROR eu.modernmt.decoder.neural.execution.NativeProcess [Thread-4] (root) unexpected EOF. The file might be corrupted.
Traceback (most recent call last):
  File "main_loop.py", line 157, in run_main
    decoder = NMTDecoder(args.model, gpu_id=args.gpu, random_seed=3435)
  File "/home/lm-dev8/MMT2/ModernMT/build/lib/pynmt/nmmt/NMTDecoder.py", line 40, in __init__
    self._engines[direction] = NMTEngine.load_from_checkpoint(model_file)
  File "/home/lm-dev8/MMT2/ModernMT/build/lib/pynmt/nmmt/NMTEngine.py", line 138, in load_from_checkpoint
    checkpoint = torch.load(data_file, map_location=lambda storage, loc: storage)
  File "/home/lm-dev8/.local/lib/python2.7/site-packages/torch/serialization.py", line 231, in load
    return _load(f, map_location, pickle_module)
  File "/home/lm-dev8/.local/lib/python2.7/site-packages/torch/serialization.py", line 386, in _load
    deserialized_objects[key]._set_from_file(f, offset)
RuntimeError: unexpected EOF. The file might be corrupted.
2017-10-20 17:12:39,739 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at eu.modernmt.decoder.neural.execution.NativeProcess.deserialize(NativeProcess.java:211)
	at eu.modernmt.decoder.neural.execution.NativeProcess.<init>(NativeProcess.java:125)
	at eu.modernmt.decoder.neural.execution.NativeProcess$Builder.start(NativeProcess.java:92)
	at eu.modernmt.decoder.neural.execution.NativeProcess$Builder.startOnGPU(NativeProcess.java:72)
	at eu.modernmt.decoder.neural.execution.StartNativeProcessGpuTask.call(StartNativeProcessGpuTask.java:34)
	at eu.modernmt.decoder.neural.execution.SingletonExecutionQueue.forGPU(SingletonExecutionQueue.java:48)
	at eu.modernmt.decoder.neural.execution.ExecutionQueue.newInstance(ExecutionQueue.java:42)
	at eu.modernmt.decoder.neural.NeuralDecoder.<init>(NeuralDecoder.java:54)
	at eu.modernmt.engine.impl.NeuralEngine.<init>(NeuralEngine.java:31)
	at eu.modernmt.engine.Engine.load(Engine.java:70)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:319)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:49)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:168)
`

**Comment by nicolabertoldi** [comment]
are you training to resume a failed training (using parameter --resume) or to re-start from scratch the training by loading an already existing checkpoint (using parameter --checkpoint)?

Which commit are you working with?  We fixed a small bug related to resuming a failed training in a very recently commit.

**Comment by AndRossi** [comment]
Hello @EtienneAb3d,

When you stopped your training, did you use kill -2 or kill -9?

If you used kill -9, then the training was not stopped gracefully, so the model files were not copied from your runtime/<your_engine>/tmp/training folder to your engines/<your_engine>/models folder.

However you can copy those files manually and your engine should work.

I hope this helps!

Andrea

**Comment by EtienneAb3d** [comment]
@nicolabertoldi, as said here, I tried to start an engine after having killed the training:
https://github.com/ModernMT/MMT/issues/287#issuecomment-338125014

@AndRossi, ok ! I just did a CTRL+C on the running command line. I will try later to copy those files...

**Comment by AndRossi** [comment]
Hello again @EtienneAb3d, 

After copying those model files, did your engine work as expected?

Andrea

**Comment by EtienneAb3d** [comment]
I still didn't find the time to test it, my urgencies being elsewhere.

**Comment by EtienneAb3d** [comment]
I just had a look at these folders. I'm puzzled by the fact that the tmp training folder seems to have a very different structure comparing to an other well trained neural model.
I'm not sure I didn't shuffle something somewhere in my folders, when managing later MMT upgrade.

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

we tried to stop an engine training before the termination-criteria and, with the latest version 2.0.1, all seems to works now!

I'm closing the issue for now but please, if you encounter a similar problem again, feel free to re-open it!

Thanks for your help,
Davide
