### ISSUE TITLE
faield with exit code 1 during engine creation from TMX files

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#310]
Hello MMT team,

I am getting this error when I try to create a new en>ja engine using tmx files. It seems it has to do with the data format for both 'creationdate' and 'changedate' values in the tmx files. 

Here is the error showing up in the terminal.

ENGINE:  enja
BILINGUAL CORPORA: 923 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > ja

> INFO: (1 of 7) Corpora cleaning...                                    ERROR Unexpected exception:
	Command 'java -Xmx43434m -cp /home/mlearner/nmt/build/mmt-2.0.2.jar -Dmmt.home=/home/mlearner/nmt -Djava.library.path=/home/mlearner/nmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ja --filters normalize punctuation odd_sentences drafts sentence_length --output /home/mlearner/nmt/runtime/enja/tmp/training/clean_corpora --input /home/mlearner/nmt/examples/data/train' failed with exit code 1

And this is the training. log

`2017-11-28 09:02:35,925 [INFO] - Training started: engine=enja, bilingual=923, monolingual=0, langpair=en-ja
2017-11-28 09:02:35,926 [DEBUG] - Shell exec: nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits --id=0
2017-11-28 09:02:35,940 [INFO] - Training step "clean_tms" (1/9) started
2017-11-28 09:02:35,940 [DEBUG] - Shell exec: java -Xmx43434m -cp /home/mlearner/nmt/build/mmt-2.0.2.jar -Dmmt.home=/home/mlearner/nmt -Djava.library.path=/home/mlearner/nmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ja --filters normalize punctuation odd_sentences drafts sentence_length --output /home/mlearner/nmt/runtime/enja/tmp/training/clean_corpora --input /home/mlearner/nmt/examples/data/train
2017-11-28 09:02:37,647 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
Exception in thread "main" java.io.IOException: Invalid TMX /home/mlearner/nmt/examples/data/train/jde_composite.tmx
	at eu.modernmt.model.corpus.impl.tmx.TMXLineReader.read(TMXLineReader.java:56)
	at eu.modernmt.training.MultilingualCorpusMask$1.read(MultilingualCorpusMask.java:39)
	at eu.modernmt.cleaning.FilteredMultilingualCorpus.initialize(FilteredMultilingualCorpus.java:99)
	at eu.modernmt.cleaning.FilteredMultilingualCorpus.getContentReader(FilteredMultilingualCorpus.java:36)
	at eu.modernmt.io.IOCorporaUtils.copy(IOCorporaUtils.java:148)
	at eu.modernmt.io.IOCorporaUtils.copy(IOCorporaUtils.java:162)
	at eu.modernmt.io.IOCorporaUtils.copy(IOCorporaUtils.java:170)
	at eu.modernmt.training.BatchCopyProcess.lambda$run$0(BatchCopyProcess.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.stream.XMLStreamException: Invalid date '11032016030226' at line 9
	at eu.modernmt.model.corpus.impl.tmx.TMXPairReader.getTimestamp(TMXPairReader.java:155)
	at eu.modernmt.model.corpus.impl.tmx.TMXPairReader.readTu(TMXPairReader.java:70)
	at eu.modernmt.model.corpus.impl.tmx.TMXPairReader.read(TMXPairReader.java:47)
	at eu.modernmt.model.corpus.impl.tmx.TMXLineReader.read(TMXLineReader.java:52)
	... 11 more
Caused by: java.text.ParseException: Unparseable date: "11032016030226"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at eu.modernmt.model.corpus.impl.tmx.TMXPairReader.getTimestamp(TMXPairReader.java:153)
	... 14 more
2017-11-28 09:02:38,168 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/mlearner/nmt/cli/mmt/engine.py", line 480, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/mlearner/nmt/cli/mmt/engine.py", line 293, in __call__
    self._f(*args, **kwargs)
  File "/home/mlearner/nmt/cli/mmt/engine.py", line 524, in _clean_tms
    args.bilingual_corpora = self._engine.cleaner.clean(args.bilingual_corpora, folder, log=log)
  File "/home/mlearner/nmt/cli/mmt/processing.py", line 81, in clean
    shell.execute(command, stdout=log, stderr=log)
  File "/home/mlearner/nmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command 'java -Xmx43434m -cp /home/mlearner/nmt/build/mmt-2.0.2.jar -Dmmt.home=/home/mlearner/nmt -Djava.library.path=/home/mlearner/nmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ja --filters normalize punctuation odd_sentences drafts sentence_length --output /home/mlearner/nmt/runtime/enja/tmp/training/clean_corpora --input /home/mlearner/nmt/examples/data/train' failed with exit code 1`

Any idea how this can be fixed/ignored?

Thanks,
Mohamed

**Comment by AndRossi** [comment]
Hello @mzeidhassan, 

Reading your log, it seems that there is a problem with a date field in one of your TMX files:  
```bash
Caused by: javax.xml.stream.XMLStreamException: Invalid date '11032016030226' at line 9 at  ...
``` 

MMT needs TMX files to follow the official TMX standard, with ISO-compliant dates.
The date pattern that MMT accepts is: `yyyyMMdd'T'HHmmss'Z'`.  
So for instance an acceptable date in a TMX file looks like `20070913T094038Z`  
(which represents Thu Sep 13 11:40:38 CEST 2007).

Andrea

**Comment by mzeidhassan** [comment]
Thanks @AndRossi for your prompt reply. Yes, I confirm that the date format is causing these errors in the files. I am currently doing a mass search and replace in the files using regex. Hope this will fix things. I am closing this issue for now. Thanks again!
