### ISSUE TITLE
decoder/vocab.vb' failed with exit code -4

### ISSUE THREAD

**Issue by letconex** [ModernMT/MMT#311]
Hi!
I just installed mmt 2.0.2 in a virtual Vbox machine, but wherever I do, I get the same error message. I also pulled the docker image and run the en it example files and always the same message. Compiling from source renders the same results. Does it have to do with the fact that it runs in a virtual machine?

ltc@ltc-VirtualBox:~/mmt$ sudo ./mmt create -e enit en it examples/data/train
=========== TRAINING STARTED ===========

ENGINE:  enit
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 3s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 3s)
INFO: (3 of 6) Context Analyzer training...                            DONE (in 2s)
INFO: (4 of 6) Aligner training...                                     DONE (in 11s)
INFO: (5 of 6) Translation Model training...                          ERROR Unexpected exception:
	Command '/home/ltc/mmt/build/bin/sapt_build --lex /home/ltc/mmt/runtime/enit/tmp/training/tm/model.tlex --input /home/ltc/mmt/runtime/enit/tmp/training/tm/corpora --model /home/ltc/mmt/engines/enit/models/decoder/sapt -s en -t it -v /home/ltc/mmt/engines/enit/models/decoder/vocab.vb' failed with exit code -4

And this is the training.log
2017-11-29 11:37:12,051 [INFO] - Training started: engine=enit, bilingual=3, monolingual=0, langpair=en-it
2017-11-29 11:37:12,057 [INFO] - Training step "clean_tms" (1/9) started
2017-11-29 11:37:12,058 [DEBUG] - Shell exec: java -Xmx5368m -cp /home/ltc/mmt/build/mmt-2.0.2.jar -Dmmt.home=/home/ltc/mmt -Djava.library.path=/home/ltc/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t it --filters normalize punctuation odd_sentences drafts sentence_length --output /home/ltc/mmt/runtime/enit/tmp/training/clean_corpora --input /home/ltc/mmt/examples/data/train
2017-11-29 11:37:12,949 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-11-29 11:37:15,701 [INFO] - Training step "clean_tms" completed in 3 s
2017-11-29 11:37:15,702 [INFO] - Training step "create_db" (2/9) started
2017-11-29 11:37:15,703 [INFO] - Training step "create_db" completed in 0 s
2017-11-29 11:37:15,704 [INFO] - Training step "preprocess" (3/9) started
2017-11-29 11:37:15,704 [DEBUG] - Shell exec: java -cp /home/ltc/mmt/build/mmt-2.0.2.jar -Dmmt.home=/home/ltc/mmt -Djava.library.path=/home/ltc/mmt/build/lib eu.modernmt.cli.TrainingPipelineMain -s en -t it --output /home/ltc/mmt/runtime/enit/tmp/training/preprocessed_corpora -v /home/ltc/mmt/engines/enit/models/decoder/vocab.vb --input /home/ltc/mmt/runtime/enit/tmp/training/training_corpora --dev /home/ltc/mmt/engines/enit/data/dev --test /home/ltc/mmt/engines/enit/data/test
2017-11-29 11:37:16,590 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-11-29 11:37:18,921 [INFO] - Training step "preprocess" completed in 3 s
2017-11-29 11:37:18,922 [INFO] - Training step "train_context" (4/9) started
2017-11-29 11:37:18,923 [DEBUG] - Shell exec: java -cp /home/ltc/mmt/build/mmt-2.0.2.jar -Dmmt.home=/home/ltc/mmt -Djava.library.path=/home/ltc/mmt/build/lib eu.modernmt.cli.ContextAnalyzerMain -s en -t it -i /home/ltc/mmt/engines/enit/models/context -c /home/ltc/mmt/runtime/enit/tmp/training/training_corpora
2017-11-29 11:37:19,798 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2017-11-29 11:37:20,402 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of memory 1
2017-11-29 11:37:20,422 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of memory 2
2017-11-29 11:37:20,448 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Bulk insert of memory 3
2017-11-29 11:37:20,449 INFO  eu.modernmt.context.lucene.storage.CorporaStorage [main] Flushing index to disk. Pending updates: 3
2017-11-29 11:37:20,452 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-1] Indexing bucket CorpusBucket{memory=3, direction=en → it}
2017-11-29 11:37:20,457 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-2] Indexing bucket CorpusBucket{memory=1, direction=en → it}
2017-11-29 11:37:20,468 INFO  eu.modernmt.context.lucene.storage.AnalysisTask [pool-2-thread-3] Indexing bucket CorpusBucket{memory=2, direction=en → it}
2017-11-29 11:37:21,283 [INFO] - Training step "train_context" completed in 2 s
2017-11-29 11:37:21,284 [INFO] - Training step "train_aligner" (5/9) started
2017-11-29 11:37:21,293 [DEBUG] - Shell exec: /home/ltc/mmt/build/bin/fa_build -s /home/ltc/mmt/runtime/enit/tmp/training/aligner/merge.en -t /home/ltc/mmt/runtime/enit/tmp/training/aligner/merge.it -m /home/ltc/mmt/engines/enit/models/aligner/en__it.mdl -I 4
Creating vocabulary... DONE in 0.0828111s
== Forward model training ==
Initial setup... DONE in 0.455892s
Iteration 1:
	Computing alignments... DONE in 0.872989s
	Optimizing diagonal tension... DONE in 0.151169s
	Normalizing translation table... DONE in 0.205669s
Iteration 2:
	Computing alignments... DONE in 0.872003s
	Optimizing diagonal tension... DONE in 0.152523s
	Normalizing translation table... DONE in 0.205541s
Iteration 3:
	Computing alignments... DONE in 0.868318s
	Optimizing diagonal tension... DONE in 0.149645s
	Normalizing translation table... DONE in 0.208374s
Iteration 4:
	Computing alignments... DONE in 0.864719s
	Optimizing diagonal tension... DONE in 0.15415s
	Normalizing translation table... DONE in 0.207399s
Pruning model... DONE in 0.0833011s

Training DONE in 5.4548s

== Backward model training ==
Initial setup... DONE in 0.453243s
Iteration 1:
	Computing alignments... DONE in 0.865606s
	Optimizing diagonal tension... DONE in 0.151675s
	Normalizing translation table... DONE in 0.206023s
Iteration 2:
	Computing alignments... DONE in 0.863668s
	Optimizing diagonal tension... DONE in 0.154943s
	Normalizing translation table... DONE in 0.205995s
Iteration 3:
	Computing alignments... DONE in 0.877201s
	Optimizing diagonal tension... DONE in 0.151214s
	Normalizing translation table... DONE in 0.206609s
Iteration 4:
	Computing alignments... DONE in 0.866969s
	Optimizing diagonal tension... DONE in 0.152194s
	Normalizing translation table... DONE in 0.206294s
Pruning model... DONE in 0.0827022s

Training DONE in 5.44734s

Writing model...DONE in 0.047801s
2017-11-29 11:37:32,482 [INFO] - Training step "train_aligner" completed in 11 s
2017-11-29 11:37:32,483 [INFO] - Training step "write_config" (6/9) started
2017-11-29 11:37:32,484 [INFO] - Training step "write_config" completed in 0 s
2017-11-29 11:37:32,484 [INFO] - Training step "train_tm" (7/9) started
2017-11-29 11:37:32,485 [DEBUG] - Shell exec: /home/ltc/mmt/build/bin/fa_align --model /home/ltc/mmt/engines/enit/models/aligner/en__it.mdl --input /home/ltc/mmt/runtime/enit/tmp/training/tm/corpora --output /home/ltc/mmt/runtime/enit/tmp/training/tm/corpora --source en --target it --strategy 1
2017-11-29 11:37:34,061 [DEBUG] - Shell exec: /home/ltc/mmt/build/bin/fa_export --model /home/ltc/mmt/engines/enit/models/aligner/en__it.mdl --output /home/ltc/mmt/runtime/enit/tmp/training/tm/model.tlex
2017-11-29 11:37:34,283 [DEBUG] - Shell exec: /home/ltc/mmt/build/bin/sapt_build --lex /home/ltc/mmt/runtime/enit/tmp/training/tm/model.tlex --input /home/ltc/mmt/runtime/enit/tmp/training/tm/corpora --model /home/ltc/mmt/engines/enit/models/decoder/sapt -s en -t it -v /home/ltc/mmt/engines/enit/models/decoder/vocab.vb
2017-11-29 11:37:34,553 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/ltc/mmt/cli/mmt/engine.py", line 480, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/ltc/mmt/cli/mmt/engine.py", line 293, in __call__
    self._f(*args, **kwargs)
  File "/home/ltc/mmt/cli/mmt/phrasebased.py", line 320, in _train_tm
    self._engine.moses.pt.train(corpora, self._engine.aligner, working_dir, log=log)
  File "/home/ltc/mmt/cli/mmt/phrasebased.py", line 183, in train
    shell.execute(command, stdout=log, stderr=log)
  File "/home/ltc/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command '/home/ltc/mmt/build/bin/sapt_build --lex /home/ltc/mmt/runtime/enit/tmp/training/tm/model.tlex --input /home/ltc/mmt/runtime/enit/tmp/training/tm/corpora --model /home/ltc/mmt/engines/enit/models/decoder/sapt -s en -t it -v /home/ltc/mmt/engines/enit/models/decoder/vocab.vb' failed with exit code -4

**Comment by AndRossi** [comment]
Hi @letconex, 

This is quite weird. It seems that the execution of sapt_build command fails. 
Could you please try to manually run the sapt_build? Maybe this way a more detailed error message will be returned.  

To manually run sapt_build first tell your bash where to find the MMT libraries:
```bash
export LD_LIBRARY_PATH=/home/ltc/mmt/build/lib/
```

After that, run the command
```bash
/home/ltc/mmt/build/bin/sapt_build \
--lex /home/ltc/mmt/runtime/enit/tmp/training/tm/model.tlex \
--input /home/ltc/mmt/runtime/enit/tmp/training/tm/corpora \
--model /home/ltc/mmt/engines/enit/models/decoder/sapt \
-s en -t it -v /home/ltc/mmt/engines/enit/models/decoder/vocab.vb
```

Thanks for your patience!

Andrea

**Comment by letconex** [comment]
Thank you for your answer:
ltc@ltc-VirtualBox:~/mmt$ /home/ltc/mmt/build/bin/sapt_build --lex /home/ltc/mmt/runtime/enit/tmp/training/tm/model.tlex --input /home/ltc/mmt/runtime/enit/tmp/training/tm/corpora --model /home/ltc/mmt/engines/enit/models/decoder/sapt -s en -t it -v /home/ltc/mmt/engines/enit/models/decoder/vocab.vb
Illegal instruction (core dumped)
And with sudo:
ltc@ltc-VirtualBox:~/mmt$ sudo /home/ltc/mmt/build/bin/sapt_build --lex /home/ltc/mmt/runtime/enit/tmp/training/tm/model.tlex --input /home/ltc/mmt/runtime/enit/tmp/training/tm/corpora --model /home/ltc/mmt/engines/enit/models/decoder/sapt -s en -t it -v /home/ltc/mmt/engines/enit/models/decoder/vocab.vb
/home/ltc/mmt/build/bin/sapt_build: error while loading shared libraries: libmmt_sapt.so: cannot open shared object file: No such file or directory

**Comment by AndRossi** [comment]
Hi @letconex,

For some reason that command can not find `libmmt_sapt.so`.
Can you please check if that file is present in your `/home/ltc/mmt/build/lib` folder?

Andrea

**Comment by letconex** [comment]
![2017-11-29-193757_1920x994_scrot](https://user-images.githubusercontent.com/25906135/33389929-0c1238ee-d53d-11e7-898f-d176f787d26d.png)
It is present...

**Comment by AndRossi** [comment]
Ok, then I believe that there was an error with command 
`export LD_LIBRARY_PATH=/home/ltc/mmt/build/lib/`

Can you please check if typing in your bash `echo $LD_LIBRARY_PATH` returns the correct path `/home/ltc/mmt/build/lib/`?

**Comment by letconex** [comment]
ltc@ltc-VirtualBox:~/ModernMT/mmt$ echo $LD_LIBRARY_PATH
/home/ltc/mmt/build/lib/

**Comment by letconex** [comment]
I followed the steps in the Wiki for the Docker install and then ran:
ltc@ltc-VirtualBox:~$ sudo docker run -it --publish 8045:8045 modernmt/master bash
[sudo] password for ltc: 
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

mmt@c743293b230e:~/mmt$ ./mmt create en it examples/data/train

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 5s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 3s)
INFO: (3 of 6) Context Analyzer training...                            DONE (in 2s)
INFO: (4 of 6) Aligner training...                                     DONE (in 11s)
INFO: (5 of 6) Translation Model training...                          ERROR Unexpected exception:
	Command '/home/mmt/mmt/build/bin/sapt_build --lex /home/mmt/mmt/runtime/default/tmp/training/tm/model.tlex --input /home/mmt/mmt/runtime/default/tmp/training/tm/corpora --model /home/mmt/mmt/engines/default/models/decoder/sapt -s en -t it -v /home/mmt/mmt/engines/default/models/decoder/vocab.vb' failed with exit code -4
I will try will a fresh install on a new partition, with no virtual environment, although I would have expected to it run from Docker...
Anyway, thank you for very much for your input.
Something puzzles me though:
Command '/home/mmt/mmt/build/bin/sapt_build...
I do not know why docker doubles mmt.
In the docker file from the 2.0.2 archive the last lines are:
# Install MMT
RUN wget -qO- https://github.com/ModernMT/MMT/releases/download/v2.0.2/mmt-2.0.2-ubuntu.tar.gz | tar xvfz -
WORKDIR /home/mmt/mmt
Is /home/mmt/mmt ok?
Anyway, I will do a fresh install and then report back if I encounter any errors, thank you very much for your time.

**Comment by AndRossi** [comment]
Hi @letconex, 

The path `/home/mmt/mmt` in the Docker installation is ok (by default, our Docker user is called `mmt` and the ModernMT home folder is called `mmt` as well.

I am puzzled by the `libmmt_sapt.so` problem, though.
I believe that the fact that your commands can not see that file is related to the VirtualBox environment, as we were not able to replicate this locally.  

Please let me know if your fresh install on a new partition goes smoothly.
I suggest you to install from sources - it's the safest way to install MMT :)

Andrea

**Comment by letconex** [comment]
Hello, I confirm it is working, I installed everything again from source in another partition and it works now.
Thank you very much for your help, you may close the issue now. Have a great day!

**Comment by AndRossi** [comment]
Hi @letconex,

I'm so glad it works fine in the new partition!  
As you suggested I'm closing this issue now, but do not hesitate to re-open it if you have any further problems with MMT :)

Have a nice day!

Andrea
