### ISSUE TITLE
TMX import failed, but a memory is being added anyway

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#328]
Hi MMT team,

I am trying to import a TMX file using this command:

`sudo ./mmt import -x /home/mlearner/Documents/TMX/AB_COR.tmx`

This command throws this error:

`Importing AB_COR... [                                        ]   0.0% 00:00  ERROR: Exception(u'HTTP request failed with code 500: http://localhost:8045/memories/9/corpus',)
IMPORT FAILED`

The strange thing is that with each failed try to import the TMX file, a new memory is created and you can see them listed under:
http://localhost:8045/memories/

So, I tried about 6 times, and each time, it fails, but a memory is added incrementally. 

Here is what I see in the node.log file. Any idea? What could be the problem?

> POST /memories/9/corpus?local_file=%2Fhome%2Fmlearner%2FDocuments%2FTMX%2FAB_COR.tmx&content_type=tmx
2017-12-14 23:15:23,882 ERROR eu.modernmt.rest.actions.memory.AddToMemoryCorpus [qtp1280977839-125] Internal error while executing action AddToMemoryCorpus
eu.modernmt.data.DataManagerException: Failed to read corpus for memory 9
	at eu.modernmt.cluster.kafka.KafkaDataManager.upload(KafkaDataManager.java:289)
	at eu.modernmt.cluster.kafka.KafkaDataManager.upload(KafkaDataManager.java:249)
	at eu.modernmt.facade.MemoryFacade.add(MemoryFacade.java:190)
	at eu.modernmt.rest.actions.memory.AddToMemoryCorpus.execute(AddToMemoryCorpus.java:34)
	at eu.modernmt.rest.actions.memory.AddToMemoryCorpus.execute(AddToMemoryCorpus.java:24)
	at eu.modernmt.rest.framework.actions.ObjectAction.getResult(ObjectAction.java:13)
	at eu.modernmt.rest.framework.actions.ObjectAction.getResult(ObjectAction.java:8)
	at eu.modernmt.rest.framework.actions.JSONAction.unsecureExecute(JSONAction.java:48)
	at eu.modernmt.rest.framework.actions.JSONAction.execute(JSONAction.java:21)
	at eu.modernmt.rest.framework.routing.RouterServlet.service(RouterServlet.java:105)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at eu.modernmt.rest.MultipartConfigInjectionHandler.handle(MultipartConfigInjectionHandler.java:49)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Invalid TMX /home/mlearner/Documents/TMX/AB_COR.tmx
	at eu.modernmt.model.corpus.impl.tmx.TMXLineReader.read(TMXLineReader.java:56)
	at eu.modernmt.cleaning.FilteredMultilingualCorpus.initialize(FilteredMultilingualCorpus.java:99)
	at eu.modernmt.cleaning.FilteredMultilingualCorpus.getContentReader(FilteredMultilingualCorpus.java:36)
	at eu.modernmt.cluster.kafka.KafkaDataManager.upload(KafkaDataManager.java:266)
	... 28 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
	at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
	at eu.modernmt.model.corpus.impl.tmx.TMXPairReader.read(TMXPairReader.java:38)
	at eu.modernmt.model.corpus.impl.tmx.TMXLineReader.read(TMXLineReader.java:52)

Again, I cannot determine what invalid in this TMX file. I have opened it a TMX editor and I don't see what is wrong. That being said, I believe no memory should be added if the import is failed. 

One last thing:

How can I delete these redundant empty memories from MMT? 

Thanks,
Mohamed

**Comment by mzeidhassan** [comment]
OK, after restarting, the import worked fine, but I am wondering why the memories' names were added under /domains or /memories although the import failed.

**Comment by AndRossi** [comment]
Hi @mzeidhassan.

Thanks for reporting this! 
I have fixed that: now if you perform `./mmt import` and the import fails, the newly created memory is immediately deleted.

You will find the fixed code in our `master` branch.

Thank you again for your great support!

Have a nice day, 

Andrea

**Comment by mzeidhassan** [comment]
Thanks @AndRossi for the quick fix!

**Comment by AndRossi** [comment]
Hi @mzeidhassan, 

I'm glad you appreciate it :D
Since this issue seems closed I'm closing it now.  
Of course feel free to re-open it if you experience more troubles on this topic.

I wish you a wonderful day!

Andrea
