### ISSUE TITLE
Issue while creating a new engine from scratch

### ISSUE THREAD

**Issue by amitdharma** [ModernMT/MMT#332]
I am a total novice and still learning to code and try my hands on this. So please excuse if I put silly questions. I have installed mmt and when trying to create an engine (normal one not neural) i get the following error. 
When I tried using the test data:
bits@ubuntu:~$  ./mmt create en it examples/data/train
bash: ./mmt: Is a directory
I then tried creating an engine (German English) where i copied one tmx file to the main directory.
./mmt create de en deen.tmx
ERROR Unexpected exception:
	OSError(17, 'File exists')
bits@ubuntu:~/mmt$ sudo ./mmt create de en deen.tmx
ERROR Unexpected exception:
	OSError(20, 'Not a directory')

When I used the debug option, I get the following
2018-01-03 14:05:00,376 [INFO] - Training started: engine=default, bilingual=1, monolingual=0, langpair=de-en
2018-01-03 14:05:00,382 [INFO] - Training step "clean_tms" (1/9) started
2018-01-03 14:05:00,383 [DEBUG] - Shell exec: java -Xmx3458m -cp /home/bits/mmt/build/mmt-2.0.2.jar -Dmmt.home=/home/bits/mmt -Djava.library.path=/home/bits/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s de -t en --filters normalize punctuation odd_sentences drafts sentence_length --output /home/bits/mmt/runtime/default/tmp/training/clean_corpora --input /home/bits/mmt/Trial/Data
2018-01-03 14:05:02,543 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
Exception in thread "main" java.lang.NullPointerException
	at eu.modernmt.training.MultilingualCorpusMask$1.read(MultilingualCorpusMask.java:45)
	at eu.modernmt.cleaning.FilteredMultilingualCorpus.initialize(FilteredMultilingualCorpus.java:99)
	at eu.modernmt.cleaning.FilteredMultilingualCorpus.getContentReader(FilteredMultilingualCorpus.java:36)
	at eu.modernmt.io.IOCorporaUtils.copy(IOCorporaUtils.java:148)
	at eu.modernmt.io.IOCorporaUtils.copy(IOCorporaUtils.java:162)
	at eu.modernmt.io.IOCorporaUtils.copy(IOCorporaUtils.java:170)
	at eu.modernmt.training.BatchCopyProcess.lambda$run$0(BatchCopyProcess.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-01-03 14:05:03,235 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/bits/mmt/cli/mmt/engine.py", line 480, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/bits/mmt/cli/mmt/engine.py", line 293, in __call__
    self._f(*args, **kwargs)
  File "/home/bits/mmt/cli/mmt/engine.py", line 524, in _clean_tms
    args.bilingual_corpora = self._engine.cleaner.clean(args.bilingual_corpora, folder, log=log)
  File "/home/bits/mmt/cli/mmt/processing.py", line 81, in clean
    shell.execute(command, stdout=log, stderr=log)
  File "/home/bits/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command 'java -Xmx3458m -cp /home/bits/mmt/build/mmt-2.0.2.jar -Dmmt.home=/home/bits/mmt -Djava.library.path=/home/bits/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s de -t en --filters normalize punctuation odd_sentences drafts sentence_length --output /home/bits/mmt/runtime/default/tmp/training/clean_corpora --input /home/bits/mmt/Trial/Data' failed with exit code 1

**Comment by AndRossi** [comment]
Hi @amitdharma,

Thanks for trying MMT! Don't worry about being a novice: questions are always welcome.

First of all, when you run any of the `./mmt` commands your bash should be positioned in your mmt home folder. So, before `./mmt create en it examples/data/train` you should run `cd mmt`.
I believe this is the reason why your first `./mmt create` command failed.

Furthermore, MMT does not currently allow to pass a single file to train an engine: you should specify a folder, and MMT will use all the files that it contains.
This is quite logical, because for your training you typically want to use a large set of parallel corpora.
So your `./mmt create de en deen.tmx` attempt fails because you are passing a single file, not a folder.
To overcome this problem you can just place your deen.tmx in a separate folder and pass the folder path  to the ./mmt create command :)

In these two cases, no training was started.

Your logs seem to refer to a separate attempt in which you specified a`/home/bits/mmt/Trial/Data` folder; does this sound possible to you? This third attempt seems to have failed due to an old bug that has been solved in a recent MMT version. 
I see that you are using  MMT version 2.0.2; updating to v2.1 should fix the problem :)
To update your MMT version:

- if you have installed MMT from sources, just run in your `mmt` main folder these commands one by one:
```bash
git pull origin master
cd src
mvn clean install
cd ..
```

- Otherwise, if you have installed MMT from binaries, all you need to do is to [install the new binaries](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#install-the-mmt-binaries).

I really hope this helps you :)

For any further doubt, don't hesitate to contact us!

Have a nice day, 

Andrea

**Comment by amitdharma** [comment]
Thanks a lot @AndRossi. 
I tried your options. This is what I got
bits@ubuntu:~/mmt$ git pull origin master
fatal: Not a git repository (or any of the parent directories): .git
bits@ubuntu:~/mmt$ sudo git pull origin master
[sudo] password for bits: 
fatal: Not a git repository (or any of the parent directories): .git
bits@ubuntu:~/mmt$ sudo ./mmt create de en Trial/Data/Train
ERROR Unexpected exception:
	OSError(2, 'No such file or directory')
bits@ubuntu:~/mmt$ sudo ./mmt create de en Trial/Data

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 1 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   de > en

INFO: (1 of 6) Corpora cleaning...                                    ERROR Unexpected exception:
	Command 'java -Xmx3458m -cp /home/bits/mmt/build/mmt-2.0.2.jar -Dmmt.home=/home/bits/mmt -Djava.library.path=/home/bits/mmt/build/lib eu.modernmt.cli.CleaningPipelineMain -s de -t en --filters normalize punctuation odd_sentences drafts sentence_length --output /home/bits/mmt/runtime/default/tmp/training/clean_corpora --input /home/bits/mmt/Trial/Data' failed with exit code 1

Do i need to download the new binaries? Or is there anything else that i can do?

**Comment by AndRossi** [comment]
Hi @amitdharma,

What happened there is that the `git pull` command failed, so MMT was not updated. 
As a consequence, there is still same error that appeared in the logs you have sent me before.
I believe that something weird has happened with your `mmt` folder in the past: it is not recognized as a git repository anymore, and that is why `git pull` failed.
My suggestion is to just install MMT from scratch again :)  

To do that, open a bash in your home folder (I believe it is `/home/ubuntu/bits`) and delete your current `mmt` installation. You can do this by running:

```bash
cd ~
rm -r mmt
```

Then you can proceed with the installation again. As I suggested before, you can use [this guide](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source). Please note that in all the install steps you should not use `sudo` unless it is said explicitly :)

After that, you should have a correct installation of the latest MMT version.

Please let me know if you manage to re-install MMT or you need further help :) 

Andrea

**Comment by amitdharma** [comment]
Hi @AndRossi 

Sorry for the late reply. I was stuck with something else and hence could not try this before. I tried removing the mmt, but nothing is working i guess. I have physically deleted the folder and trying to install from scratch.

**Comment by amitdharma** [comment]
Hi @AndRossi,

I could install it. :) But when I try to create a sample engine, I am getting this error.
bits@ubuntu:~/ModernMT$ ./mmt create de en Trial/deen technical 1.tmx
ERROR Unexpected exception:
	OSError(2, 'No such file or directory')
bits@ubuntu:~/ModernMT$ ./mmt create de en Trial/deen technical 1
ERROR Unexpected exception:
	OSError(2, 'No such file or directory')
bits@ubuntu:~/ModernMT$ ./mmt create de en Trial

=========== TRAINING STARTED ===========

ENGINE:  default
BILINGUAL CORPORA: 1 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   de > en

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 23s)
INFO: (2 of 6) Corpora pre-processing...                              ERROR Corpus not found: Could not find any valid de -> en segments in your input.
What could be the reason? The TMX file has relevant segments. Or do I need to change some settings.

**Comment by amitdharma** [comment]
Details of the log file
2018-01-15 14:22:04,138 [INFO] - Training started: engine=default, bilingual=1, monolingual=0, langpair=de-en
2018-01-15 14:22:04,142 [INFO] - Training step "clean_tms" (1/9) started
2018-01-15 14:22:04,143 [DEBUG] - Shell exec: java -Xmx3458m -cp /home/bits/ModernMT/build/mmt-2.2.jar -Dmmt.home=/home/bits/ModernMT -Djava.library.path=/home/bits/ModernMT/build/lib eu.modernmt.cli.CleaningPipelineMain -s de -t en --output /home/bits/ModernMT/runtime/default/tmp/training/clean_corpora --input /home/bits/ModernMT/Trial
2018-01-15 14:22:04,760 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
2018-01-15 14:22:27,542 [INFO] - Training step "clean_tms" completed in 23 s
2018-01-15 14:22:27,542 [INFO] - Training step "create_db" (2/9) started
2018-01-15 14:22:27,543 [INFO] - Training step "create_db" completed in 0 s
2018-01-15 14:22:27,578 [INFO] - Training step "preprocess" (3/9) started
2018-01-15 14:22:27,579 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/bits/ModernMT/cli/mmt/engine.py", line 481, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/bits/ModernMT/cli/mmt/engine.py", line 293, in __call__
    self._f(*args, **kwargs)
  File "/home/bits/ModernMT/cli/mmt/engine.py", line 564, in _preprocess
    (self._engine.source_lang, self._engine.target_lang))
CorpusNotFoundInFolderException: Could not find any valid de -> en segments in your input.

**Comment by AndRossi** [comment]
Hi @amitdharma, 

I'm glad you managed to re-install MMT.

The error you are experiencing now is caused by the fact that MMT filters out the low quality segments from your corpora;  it seems that in your case, all de -> en segments have been filtered out.

You can find a solutions for this problem in issue #335, that refers to exactly the same problem :) 
I have also adding an entry on this in our [FAQs page](/ModernMT/MMT/wiki/FAQs#q-during-engine-creation-the-pre-processing-step-throws-a-corpus-not-found-error-what-can-i-do) :) 

Please let me know if you manage to train your engine!

Have a nice day :)

Andrea

**Comment by amitdharma** [comment]
Hi @AndRossi 

Will take a look. Another question (since I am an absolutely novice): Is there any kind of webinar, online training available to learn and deploy modernMT? Are there any other skills that one needs to acquire (e.g. python programming)?

**Comment by AndRossi** [comment]
Hi @amitdharma, 

In February there will be a MateCat webinar about ModernMT, but I believe it will mostly involve how to connect MateCat to ModernMT.
As for the ModernMT deployment, you can find some guidance in our [install page](https://github.com/ModernMT/MMT/blob/master/INSTALL.md) and [configuration page](https://github.com/ModernMT/MMT/wiki/Advanced-Configurations). 
And of course for any doubt don't hesitate to write us :) 

Andrea

**Comment by AndRossi** [comment]
Hi again @amitdharma, 

I'm closing this issue due to inactivity now.
If you have more troubles or need further support on this topic, however, do not hesitate to re-open it :) 

Have a wonderful day!

Andrea
