### ISSUE TITLE
Failed to build MMT on CentOS

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#334]
Hi MMT team,

I am trying to install MMT from source on a new server. I get this error when I reach 'mvn clean install" command and specifically at `FastAlign-based aligner implementation` step.

Any idea what's wrong here?

> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (cmake-generate) on project mmt-aligner-fastalign: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (cmake-generate) on project mmt-aligner-fastalign: Command execution failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:276)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:660)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:265)
        ... 21 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mmt-aligner-fastalign

Thanks,
Mohamed

**Comment by AndRossi** [comment]
Hello @mzeidhassan, 

This is really weird.
Are you sure that the [installation of the third party libraries](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source) was successful?
Were the [git sumbodule commands and compile script](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#install-mmt) successful as well?

Andrea

**Comment by mzeidhassan** [comment]
@AndRossi 

Thanks for your follow-up. I forgot to mention that this machine has Oracle Linux on it. 

I managed to install all dependencies as far as I can tell. I think the only that I had a problem with is this one 'libsparsehash-dev'. I couldn't find how to install using yum. Could this be the reason? From the log file, which library could cause such issue? 

The git submodule commands worked just fine by the way. 

I would like to install from source so that I can fetch updates as we go. 

Do you think I should go with Option 2 - Install Binaries on Your Server?

Thanks for your help!
Mohamed

**Comment by mzeidhassan** [comment]
Hi @AndRossi ,

Just to confirm that the binary version worked just fine. 

To overcome the maven issue on Centos, you need to alter the POM to call cmake3 instead of cmake.

MMT installation from source still fails though because it complains about the boost library. 

It seems that Centos is not up-to-date with libraries as it's the case with Ubuntu. 

The current boost version on this instance is 'boost-devel-1.53.0-27.el7.x86_64'. Do you know which version of boost should be used to make it work? I can try installing it from source if possible.

Thanks,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

MMT requires Boost library version to be at least 1.55.0.

Cheers,
Davide

**Comment by mzeidhassan** [comment]
Thanks @davidecaroselli  for letting me know. It seems that the [latest version](https://rpmfind.net/linux/rpm2html/search.php?query=boost-devel) for Boost library on Centos is 1.53. 

You may close this issue for now.  Thanks for support!

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 
If the binary version of MMT works also on CentOS, you should be able to build MMT on your Ubuntu machine and then deploy it on the CentOS one.

You can build MMT directly from master branch with the script [extras/make_release](https://github.com/ModernMT/MMT/blob/master/extras/make_release):
```bash
./make_release mmt-myversion
```

this will create a file called `mmt-myversion.tar.gz` that is exactly the same as our builds.

Davide

**Comment by mzeidhassan** [comment]
Thanks a million @davidecaroselli for this great advice! The main reason to install from source though was to be able to update MMT whenever there is new updates, but I think this workaround would do for now. Thanks again!

**Comment by davidecaroselli** [comment]
Happy to help you!

I'm closing the issue but, as always, feel free to re-open it if you have any other questions.

Cheers,
Davide

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli ,

I am sorry for reopening this issue.

I was trying to run an SMT engine created on Ubuntu, but it failed to load.

I believe the reason could be attributed to the aligner. In NMT, I disabled the aligner, so that's why the neural engines are working just fine, but it seems this is not working for the SMT engine.

Here is the node.log output. 

Is there anything that can be done to make it run on Centos?

Thanks,
Mohamed

> 2018-01-18 18:15:09,750 INFO  com.hazelcast.core.LifecycleService [main] [10.0.2.2]:5020 [eu.modernmt] [3.9.1] [10.0.2.2]:5020 is STARTED
2018-01-18 18:15:09,751 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined the cluster in 0.688s
2018-01-18 18:15:09,752 WARN  eu.modernmt.cluster.ClusterNode [main] Model syncing not supported in this version!
2018-01-18 18:15:09,753 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2018-01-18 18:15:09,770 ERROR eu.modernmt.aligner.fastalign.FastAlign [main] Unable to load library 'mmt_fastalign'
java.lang.UnsatisfiedLinkError: Spanish_SMT_2/build/lib/libmmt_fastalign.so: libboost_filesystem.so.1.58.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at eu.modernmt.aligner.fastalign.FastAlign.<clinit>(FastAlign.java:29)
	at eu.modernmt.engine.Engine.<init>(Engine.java:115)
	at eu.modernmt.engine.impl.PhraseBasedEngine.<init>(PhraseBasedEngine.java:26)
	at eu.modernmt.engine.Engine.load(Engine.java:72)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:314)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:49)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:168)
2018-01-18 18:15:09,770 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
java.lang.UnsatisfiedLinkError: /scratch/mohamed/Spanish_SMT_2/build/lib/libmmt_fastalign.so: libboost_filesystem.so.1.58.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at eu.modernmt.aligner.fastalign.FastAlign.<clinit>(FastAlign.java:29)
	at eu.modernmt.engine.Engine.<init>(Engine.java:115)
	at eu.modernmt.engine.impl.PhraseBasedEngine.<init>(PhraseBasedEngine.java:26)
	at eu.modernmt.engine.Engine.load(Engine.java:72)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:314)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:49)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:168)

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

unfortunately this means that the build on Ubuntu is not compatible with a CentOS system. I see no other option to find out a way to build MMT directly on CentOS or, of course, switch to a Ubuntu server.

Davide

**Comment by mzeidhassan** [comment]
@davidecaroselli I see. Ubuntu is much better indeed. Thanks again Davide for your help! You can close this issue now. As always, grateful to your amazing support!
