### ISSUE TITLE
Aligner unavailable

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#339]
Hello MMT team,

I am not sure if you made any changes to the code regarding Aligner. As you may remember, I created my neural engine without aligning step, i.e. skipped it and added `<aligner enabled="false" />`  in engine.xconf file. 

I have just updated MMT version and for some reason, my engine doesn't start. Here is what I see in the node.log. 

Thanks,
Mohamed 

> 2018-01-25 14:49:37,963 INFO  com.hazelcast.core.LifecycleService [main] [192.168.1.235]:5016 [eu.modernmt] [3.9.1] [192.168.1.235]:5016 is STARTED
2018-01-25 14:49:37,964 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined the cluster in 0.37s
2018-01-25 14:49:37,964 WARN  eu.modernmt.cluster.ClusterNode [main] Model syncing not supported in this version!
2018-01-25 14:49:37,964 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2018-01-25 14:49:38,257 INFO  eu.modernmt.decoder.neural.execution.NativeProcess [Thread-4] (nmmt.NMTDecoder) Loading "en__ar" model from checkpoint... START
2018-01-25 14:49:45,390 INFO  eu.modernmt.decoder.neural.execution.NativeProcess [Thread-4] (nmmt.NMTDecoder) Loading "en__ar" model from checkpoint END 7.14s
2018-01-25 14:49:45,391 INFO  eu.modernmt.cluster.ClusterNode [main] Model loaded in 7.427s
2018-01-25 14:49:45,391 INFO  eu.modernmt.cluster.ClusterNode [main] Starting embedded Kafka process
2018-01-25 14:49:48,410 INFO  eu.modernmt.cluster.ClusterNode [main] Embedded Kafka started in 3.019s
2018-01-25 14:49:48,413 INFO  eu.modernmt.cluster.ClusterNode [main] Connecting to dataManager...
2018-01-25 14:49:48,745 INFO  eu.modernmt.cluster.kafka.KafkaDataManager [Thread-5] Channel 'memory-upload-stream' seek to position 0
2018-01-25 14:49:48,745 INFO  eu.modernmt.cluster.kafka.KafkaDataManager [Thread-5] Channel 'contributions-stream' seek to position 1
2018-01-25 14:49:48,746 INFO  eu.modernmt.cluster.ClusterNode [main] Connected to the dataManager in 0.333s
2018-01-25 14:49:48,746 INFO  eu.modernmt.cluster.ClusterNode [main] Starting sync from data stream
2018-01-25 14:49:48,876 ERROR eu.modernmt.cluster.kafka.KafkaDataManager [DataPollingThread] Unexpected exception while data-stream polling
java.lang.UnsupportedOperationException: Aligner unavailable
	at eu.modernmt.engine.Engine.getAligner(Engine.java:140)
	at eu.modernmt.cluster.kafka.KafkaDataBatch$DataPartition.process(KafkaDataBatch.java:167)
	at eu.modernmt.cluster.kafka.KafkaDataBatch.load(KafkaDataBatch.java:96)
	at eu.modernmt.cluster.kafka.DataPollingThread.run(DataPollingThread.java:136)

**Comment by mzeidhassan** [comment]
One more thing:
Is this command still supported to import tmx files from a folder?

`./mmt import --path /home/Documents/TMX/`

I noticed that there is an infinite loop happening during import and after that, it seems the engine gets corrupted. I think I will need to retrain this engine from scratch because I am starting to have issues with it. What do you think?

Thanks,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

regarding the Aligner: starting from MMT v2.3, as reported in the compatibility notes of this release, Aligner is no longer optional.
Good news are that you don't have to retrain all from scratch to fix this: you can simply run the command:
```
./mmt create <source_lang> <target_lang> /path/to/your/training/data -s clean_tms preprocess train_aligner
```
once completed you can simply copy the aligner models in `engines/default/models/aligner` into the existing engine.

For the second problem, I think is related to the missing Aligner that is now used for the import, so if you fix that, you should be able to import your TMs properly.

Let me know if this solved your issue and if I can help you further!

Best,
Davide

**Comment by mzeidhassan** [comment]
Thank you so much @davidecaroselli for your continuous support. Glad to know that there is a workaround.

You ma close this issue now and I will reopen if I encountered any issues with your solution.

Thanks again!
Mohamed
