### ISSUE TITLE
Installation issue: port already in use

### ISSUE THREAD

**Issue by lennart-tondeleir** [ModernMT/MMT#340]
Hi!

I tried installing ModernMT, since it looks very interesting. However, the test system is refusing to start. Sorry if I am missing something obvious, I am still learning...

First I tried installing the binaries but I couldn't get that to work so I installed from source. I am able to create the test engine as described on the Readme page, but when I use the start command I get an error when loading the models. Since the runtime log mentions port already used, I tried specifying different ports, but to no avail.

I would really appreciate any help or tips to get this working!

PS: working on Windows WSL

Runtime log:

`2018-01-30 13:47:02,392 INFO  eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
2018-01-30 13:47:02,938 INFO  com.hazelcast.instance.AddressPicker [main] [LOCAL] [eu.modernmt] [3.9.1] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: []
2018-01-30 13:47:02,939 INFO  com.hazelcast.instance.AddressPicker [main] [LOCAL] [eu.modernmt] [3.9.1] Prefer IPv4 stack is true.
2018-01-30 13:47:02,939 WARN  com.hazelcast.instance.AddressPicker [main] [LOCAL] [eu.modernmt] [3.9.1] Could not find a matching address to start with! Picking one of non-loopback addresses.
2018-01-30 13:47:02,958 INFO  com.hazelcast.instance.AddressPicker [main] [LOCAL] [eu.modernmt] [3.9.1] Picked [169.254.22.243]:5018, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5018], bind any local is true
2018-01-30 13:47:02,959 INFO  com.hazelcast.instance.AddressPicker [main] [LOCAL] [eu.modernmt] [3.9.1] Using public address: [192.168.232.1]:5018
2018-01-30 13:47:02,978 INFO  com.hazelcast.system [main] [192.168.232.1]:5018 [eu.modernmt] [3.9.1] Hazelcast 3.9.1 (20171130 - feca534) starting at [192.168.232.1]:5018
2018-01-30 13:47:02,978 INFO  com.hazelcast.system [main] [192.168.232.1]:5018 [eu.modernmt] [3.9.1] Copyright (c) 2008-2017, Hazelcast, Inc. All Rights Reserved.
2018-01-30 13:47:02,978 INFO  com.hazelcast.system [main] [192.168.232.1]:5018 [eu.modernmt] [3.9.1] Configured Hazelcast Serialization version: 1
2018-01-30 13:47:03,274 INFO  com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator [main] [192.168.232.1]:5018 [eu.modernmt] [3.9.1] Backpressure is disabled
2018-01-30 13:47:03,995 INFO  com.hazelcast.instance.Node [main] [192.168.232.1]:5018 [eu.modernmt] [3.9.1] Creating TcpIpJoiner
2018-01-30 13:47:04,270 INFO  com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl [main] [192.168.232.1]:5018 [eu.modernmt] [3.9.1] Starting 4 partition threads and 3 generic threads (1 dedicated for priority tas$2018-01-30 13:47:04,275 INFO  com.hazelcast.internal.diagnostics.Diagnostics [main] [192.168.232.1]:5018 [eu.modernmt] [3.9.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2018-01-30 13:47:04,283 INFO  com.hazelcast.core.LifecycleService [main] [192.168.232.1]:5018 [eu.modernmt] [3.9.1] [192.168.232.1]:5018 is STARTING
2018-01-30 13:47:04,317 INFO  com.hazelcast.system [main] [192.168.232.1]:5018 [eu.modernmt] [3.9.1] Cluster version set to 3.9
2018-01-30 13:47:04,318 INFO  com.hazelcast.internal.cluster.ClusterService [main] [192.168.232.1]:5018 [eu.modernmt] [3.9.1]

Members {size:1, ver:1} [
        Member [192.168.232.1]:5018 - 087ef5c1-2260-4479-86e6-911a9177b163 this
]

2018-01-30 13:47:04,362 INFO  com.hazelcast.core.LifecycleService [main] [192.168.232.1]:5018 [eu.modernmt] [3.9.1] [192.168.232.1]:5018 is STARTED
2018-01-30 13:47:04,366 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined the cluster in 1.497s
2018-01-30 13:47:04,368 WARN  eu.modernmt.cluster.ClusterNode [main] Model syncing not supported in this version!
2018-01-30 13:47:04,370 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2018-01-30 13:47:04,999 INFO  eu.modernmt.cluster.ClusterNode [main] Model loaded in 0.629s
2018-01-30 13:47:05,000 INFO  eu.modernmt.cluster.ClusterNode [main] Starting embedded Kafka process
2018-01-30 13:47:05,011 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
eu.modernmt.engine.BootstrapException: java.io.IOException: Port 9094 is already in use by another process
        at eu.modernmt.cluster.kafka.EmbeddedKafka.start(EmbeddedKafka.java:36)
        at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:340)
        at eu.modernmt.facade.ModernMT.start(ModernMT.java:53)
        at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:168)
Caused by: java.io.IOException: Port 9094 is already in use by another process
        at eu.modernmt.cluster.kafka.EmbeddedKafka.start(EmbeddedKafka.java:59)
        at eu.modernmt.cluster.kafka.EmbeddedKafka.start(EmbeddedKafka.java:32)
        ... 3 more`

**Comment by davidecaroselli** [comment]
Hi @lennart-tondeleir and welcome to MMT community! :)

I never worked with Windows WSL so I'm assuming that this is not an issue of the tool, otherwise I won't be able to help you. My guess is that with a previous /failed) attempt to start MMT, something is still up and running.

I suggest to run `killall -9 java`, this will immediately terminate all Java processes. After done that, run again `./mmt start` and let me know if this solved your issue.

**Comment by lennart-tondeleir** [comment]
Hi David, thank you for your quick response! Afraid not... The first command gave 'no process found' and starting still doesn't work.

I will retrace my steps on a regular linux machine without WSL, I'll keep you posted!

**Comment by davidecaroselli** [comment]
Ok, so I believe you already tried but, just in case, try to run MMT changing the ports:
```
./mmt start -p 8046 --cluster-port 5017 --datastream-port 9093 --db-port 9043
```
If even this does not fix the problem, I think that it could be the case that Windows WSL must be configured somehow.

**Comment by lennart-tondeleir** [comment]
Hi, I came across a lot of similar issues for WSL so I think you're right (could be due to firewall or IPV6_V6ONLY setting).

For now I went ahead and installed MMT on a VirtualBox VM and it is working!

Thanks again for your suggestions.
