### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: EN

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#342]
Hello MMT team,

I am using the latest version (installed from source) to build a neural engine. I monitored the CPU and Memory usage and it didn't reach its maximum capacity. I have also enabled a swap file, just in case, but it failed for some reason during the cleaning phase.

Under ModernMT/runtime/default/tmp/training/clean_corpora, I see 9 out of the 19 training data there, amongst the biggest bilingual data file there. 

Under log directory, there is only one file created 'training.log' and here's the output there:

> 2018-02-02 10:26:26,090 [INFO] - Training started: engine=default, bilingual=19, monolingual=0, langpair=en-ar
2018-02-02 10:26:26,090 [DEBUG] - Shell exec: nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits --id=0
2018-02-02 10:26:26,099 [INFO] - Training step "clean_tms" (1/10) started
2018-02-02 10:26:26,099 [DEBUG] - Shell exec: java -Xmx43434m -cp /opt/Arabic_ModernMT/build/mmt-2.3.jar -Dmmt.home=/opt/Arabic_ModernMT -Djava.library.path=/opt/Arabic_ModernMT/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ar --output /opt/Arabic_ModernMT/runtime/default/tmp/training/clean_corpora --input /opt/Arabic_ModernMT/examples/data/train
2018-02-02 10:26:26,299 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
Exception in thread "main" java.lang.IllegalArgumentException: EN
	at eu.modernmt.lang.Language.fromString(Language.java:89)
	at eu.modernmt.model.corpus.impl.tmx.LanguageCache.get(LanguageCache.java:55)
	at eu.modernmt.model.corpus.impl.tmx.TMXPairReader.readTu(TMXPairReader.java:101)
	at eu.modernmt.model.corpus.impl.tmx.TMXPairReader.read(TMXPairReader.java:47)
	at eu.modernmt.model.corpus.impl.tmx.TMXLineReader.read(TMXLineReader.java:52)
	at eu.modernmt.training.MultilingualCorpusMask$1.read(MultilingualCorpusMask.java:39)
	at eu.modernmt.cleaning.FilteredMultilingualCorpus.initialize(FilteredMultilingualCorpus.java:99)
	at eu.modernmt.cleaning.FilteredMultilingualCorpus.getContentReader(FilteredMultilingualCorpus.java:36)
	at eu.modernmt.io.IOCorporaUtils.copy(IOCorporaUtils.java:148)
	at eu.modernmt.io.IOCorporaUtils.copy(IOCorporaUtils.java:162)
	at eu.modernmt.io.IOCorporaUtils.copy(IOCorporaUtils.java:170)
	at eu.modernmt.training.BatchCopyProcess.lambda$run$0(BatchCopyProcess.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-02-02 11:12:47,611 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/opt/Arabic_ModernMT/cli/mmt/engine.py", line 481, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/opt/Arabic_ModernMT/cli/mmt/engine.py", line 293, in __call__
    self._f(*args, **kwargs)
  File "/opt/Arabic_ModernMT/cli/mmt/engine.py", line 525, in _clean_tms
    args.bilingual_corpora = self._engine.cleaner.clean(args.bilingual_corpora, folder, log=log)
  File "/opt/Arabic_ModernMT/cli/mmt/processing.py", line 80, in clean
    shell.execute(command, stdout=log, stderr=log)
  File "/opt/Arabic_ModernMT/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command 'java -Xmx43434m -cp /opt/Arabic_ModernMT/build/mmt-2.3.jar -Dmmt.home=/opt/Arabic_ModernMT -Djava.library.path=/opt/Arabic_ModernMT/build/lib eu.modernmt.cli.CleaningPipelineMain -s en -t ar --output /opt/Arabic_ModernMT/runtime/default/tmp/training/clean_corpora --input /opt/Arabic_ModernMT/examples/data/train' failed with exit code 1

Thanks for your support!

Mohamed

**Comment by mzeidhassan** [comment]
I also noticed that rerunning the command again with --resume flag, all files under 'tmp/training/clean_corpora' are deleted and everything is recreated from scratch. Does the --resume flag support the corpora cleaning phase?

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan ,

for the language codes we are compliant with ISO 639 standard, this means that language must be lowercase, while dialect must be uppercase. For this reason "EN" is invalid, "en" or "en-US" are.

Cheers,
Davide

**Comment by davidecaroselli** [comment]
`--resume` flag can resume from the latest successful step, if cleaning step did not end well, it is re-run entirely.

**Comment by mzeidhassan** [comment]
@davidecaroselli Thank you so much for your reply.
You mean that there is "EN" language code in my corpora files that is causing this issue, right?

**Comment by davidecaroselli** [comment]
Yes, that's my guess! Try to search for it, remove it and then lunch again.

Let me know if you succeed!
Davide

**Comment by davidecaroselli** [comment]
Sorry, with "remove it" I meant change it with "en" :)

**Comment by mzeidhassan** [comment]
Thanks @davidecaroselli! When I opened the files, the source was en and target is ar, but using grep to search for EN and EN-US, I found some hidden in some TUs. 'srclang="EN", 'lang="EN", etc. This is strange and the TMX indeed had some issues.

I replaced them using sed and it's working fine now, at least the cleaning phase :-) 
Thanks again for your support, Davide :+1:

**Comment by davidecaroselli** [comment]
Great! After the cleaning step completed successfully, you are 100% sure that the original data was ok, so the rest of the training should run smoothly. If this isn't the case, please feel free to re-open this issue!

Have a nice weekend,
Davide
