### ISSUE TITLE
Error training example engine

### ISSUE THREAD

**Issue by alexpangeanic** [ModernMT/MMT#353]
Hi MMT team,

I've installed MMT v2.4 binaries on a new server with Ubuntu 16.04. Trying to train the example engine provided by default, I get next error. Can you help me to resolve this?

```
$ ./mmt create -e test en it examples/data/train/

=========== TRAINING STARTED ===========

ENGINE:  test
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 3s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 2s)
INFO: (3 of 6) Context Analyzer training...                            DONE (in 1s)
INFO: (4 of 6) Aligner training...                                     DONE (in 4s)
INFO: (5 of 6) Translation Model training...
ERROR Unexpected exception:
        Command '/home/pangeanic/mmt/build/bin/sapt_build --lex /home/pangeanic/mmt/runtime/test/tmp/training/tm/model.tlex --input /home/pangeanic/mmt/runtime/test/tmp/training/tm/corpora --model /home/pangeanic/mmt/engines/test/models/decoder/sapt -s en -t it -v /home/pangeanic/mmt/engines/test/models/decoder/vocab.vb' failed with exit code -4

Traceback (most recent call last):
  File "./mmt", line 846, in <module>
    main()
  File "./mmt", line 792, in main
    actions[command](args)
  File "./mmt", line 186, in main_create
    training.start()
  File "/home/pangeanic/mmt/cli/training.py", line 63, in start
    self._builder.build(self)
  File "/home/pangeanic/mmt/cli/mmt/engine.py", line 402, in build
    self._build(resume=False, listener=listener)
  File "/home/pangeanic/mmt/cli/mmt/engine.py", line 482, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/pangeanic/mmt/cli/mmt/engine.py", line 294, in __call__
    self._f(*args, **kwargs)
  File "/home/pangeanic/mmt/cli/mmt/phrasebased.py", line 320, in _train_tm
    self._engine.moses.pt.train(corpora, self._engine.aligner, working_dir, log=log)
  File "/home/pangeanic/mmt/cli/mmt/phrasebased.py", line 183, in train
    shell.execute(command, stdout=log, stderr=log)
  File "/home/pangeanic/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
cli.libs.shell.ShellError: Command '/home/pangeanic/mmt/build/bin/sapt_build --lex /home/pangeanic/mmt/runtime/test/tmp/training/tm/model.tlex --input /home/pangeanic/mmt/runtime/test/tmp/training/tm/corpora --model /home/pangeanic/mmt/engines/test/models/decoder/sapt -s en -t it -v /home/pangeanic/mmt/engines/test/models/decoder/vocab.vb' failed with exit code -4
```
I see this error in mmt/runtime/test/logs/training.log:
```
== Backward model training ==
Initial setup... DONE in 0.212584s
Iteration 1:
        Computing alignments... DONE in 0.108556s
        Optimizing diagonal tension... DONE in 0.0289819s
        Normalizing translation table... DONE in 0.34735s
Iteration 2:
        Computing alignments... DONE in 0.114801s
        Optimizing diagonal tension... DONE in 0.0332708s
        Normalizing translation table... DONE in 0.347645s
Iteration 3:
        Computing alignments... DONE in 0.116061s
        Optimizing diagonal tension... DONE in 0.0332689s
        Normalizing translation table... DONE in 0.347978s
Iteration 4:
        Computing alignments... DONE in 0.11181s
        Optimizing diagonal tension... DONE in 0.0332601s
        Normalizing translation table... DONE in 0.349145s
Pruning model... DONE in 0.0260119s

Training DONE in 2.21196s

Writing model...DONE in 0.025722s
2018-03-06 12:49:27,620 [INFO] - Training step "train_aligner" completed in 4 s
2018-03-06 12:49:27,621 [INFO] - Training step "write_config" (6/9) started
2018-03-06 12:49:27,621 [INFO] - Training step "write_config" completed in 0 s
2018-03-06 12:49:27,622 [INFO] - Training step "train_tm" (7/9) started
2018-03-06 12:49:27,623 [DEBUG] - Shell exec: /home/pangeanic/mmt/build/bin/fa_align --model /home/pangeanic/mmt/engines/test/models/aligner/en__it.mdl --input /home/pangeanic/mmt/runtime/test/tmp/training/tm/corpora --output /home/pangeanic/mmt/runtime/test/tmp/training/tm/corpora --source en --target it --strategy 1
2018-03-06 12:49:28,141 [DEBUG] - Shell exec: /home/pangeanic/mmt/build/bin/fa_export --model /home/pangeanic/mmt/engines/test/models/aligner/en__it.mdl --output /home/pangeanic/mmt/runtime/test/tmp/training/tm/model.tlex
2018-03-06 12:49:28,433 [DEBUG] - Shell exec: /home/pangeanic/mmt/build/bin/sapt_build --lex /home/pangeanic/mmt/runtime/test/tmp/training/tm/model.tlex --input /home/pangeanic/mmt/runtime/test/tmp/training/tm/corpora --model /home/pangeanic/mmt/engines/test/models/decoder/sapt -s en -t it -v /home/pangeanic/mmt/engines/test/models/decoder/vocab.vb
Lexical model import DONE in 0.103695s
2018-03-06 12:49:28,773 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/pangeanic/mmt/cli/mmt/engine.py", line 482, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/pangeanic/mmt/cli/mmt/engine.py", line 294, in __call__
    self._f(*args, **kwargs)
  File "/home/pangeanic/mmt/cli/mmt/phrasebased.py", line 320, in _train_tm
    self._engine.moses.pt.train(corpora, self._engine.aligner, working_dir, log=log)
  File "/home/pangeanic/mmt/cli/mmt/phrasebased.py", line 183, in train
    shell.execute(command, stdout=log, stderr=log)
  File "/home/pangeanic/mmt/cli/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command '/home/pangeanic/mmt/build/bin/sapt_build --lex /home/pangeanic/mmt/runtime/test/tmp/training/tm/model.tlex --input /home/pangeanic/mmt/runtime/test/tmp/training/tm/corpora --model /home/pangeanic/mmt/engines/test/models/decoder/sapt -s en -t it -v /home/pangeanic/mmt/engines/test/models/decoder/vocab.vb' failed with exit code -4
```

Best regards,
Alex

**Comment by davidecaroselli** [comment]
Hi Alex!

long story short: try to install MMT from source re-compiling the package - instructions are available at [INSTALL.md - Installing from source](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#option-3---installing-from-source).

More in details: the phrase-based version has some low-level code that relies on specific hardware. for optimization purposes. We make our builds on our hardware, but sometimes this is not compatible with other consumer machines. Re-compiling from scratch you should avoid this problem.

If you plan to train **neural engines** this is not required, you just have to specify the `--neural` option to MMT create:
```
./mmt create -e test en it examples/data/train/ --neural
```

You can check [Hardware requirements here](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#hw-requirements) and be sure to follow the [Pre-installation steps](https://github.com/ModernMT/MMT/blob/master/INSTALL.md#pre-installation-actions)

**Comment by alexpangeanic** [comment]
Hi Davide,

Thanks for your answer, I'm going to try it.

BR,
Alex

**Comment by alexpangeanic** [comment]
Hi Davide,

Right now I'm with the compilation and I get this error in the "./compile" because Cassandra 3.11.0 isn't available anymore on the Apache site:

```
Installing RocksDB...

  GEN      util/build_version.cc
install -d /home/pangeanic/ModernMT/vendor/../build/lib
for header_dir in `find "include/rocksdb" -type d`; do \
        install -d /home/pangeanic/ModernMT/vendor/../build/$header_dir; \
done
for header in `find "include/rocksdb" -type f -name *.h`; do \
        install -C -m 644 $header /home/pangeanic/ModernMT/vendor/../build/$header; \
done
install -C -m 755 librocksdb.so.4.13.5 /home/pangeanic/ModernMT/vendor/../build/lib && \
        ln -fs librocksdb.so.4.13.5 /home/pangeanic/ModernMT/vendor/../build/lib/librocksdb.so.4.13 && \
        ln -fs librocksdb.so.4.13.5 /home/pangeanic/ModernMT/vendor/../build/lib/librocksdb.so.4 && \
        ln -fs librocksdb.so.4.13.5 /home/pangeanic/ModernMT/vendor/../build/lib/librocksdb.so
RocksDB successfully installed


Building RocksDB...

  GEN      util/build_version.cc
make: No se hace nada para 'shared_lib'.
RocksDB successfully built


Installing Cassandra 3.11.0...

Traceback (most recent call last):
  File "./compile", line 350, in <module>
    run_all()
  File "./compile", line 314, in run_all
    install_cassandra()
  File "./compile", line 270, in install_cassandra
    install_apache_lib(cassandra_apache_path, cassandra_home)
  File "./compile", line 175, in install_apache_lib
    apache_download(path, tar_destination, apache_connect(path))
  File "./compile", line 166, in apache_download
    raise Exception('Failed to download ' + apache_path)
Exception: Failed to download /cassandra/3.11.0/apache-cassandra-3.11.0-bin.tar.gz
```

![image](https://user-images.githubusercontent.com/36639685/37038748-ed800e8c-2155-11e8-8804-f0ddf0663576.png)

Cassandra 3.11.2 is available: http://www.apache.org/dyn/closer.lua/cassandra/3.11.2/apache-cassandra-3.11.2-bin.tar.gz

Changing "CASSANDRA_VERSION = '3.11.0'" to "CASSANDRA_VERSION = '3.11.2'" makes the compilation work.

BR,
Alex

**Comment by davidecaroselli** [comment]
.. great!

We will change the Cassandra version ASAP (thanks for the report!) meanwhile you can just copy the cassandra and kafka folders from the *binary version* you already have: same folder names inside `vendor`.

It should work! Let me know if this does the trick.

**Comment by alexpangeanic** [comment]
Hi Davide,

After compiling/installing, I've got another error related to cassandra. I've needed to change also the pom.xml:
"<cassandra.version>3.11.0</cassandra.version>" to " <cassandra.version>3.11.2</cassandra.version>"

```
$ ./mmt create -e test en it examples/data/train

=========== TRAINING STARTED ===========

ENGINE:  test
BILINGUAL CORPORA: 3 documents
MONOLINGUAL CORPORA: 0 documents
LANGS:   en > it

INFO: (1 of 6) Corpora cleaning...                                     DONE (in 3s)
INFO: (2 of 6) Corpora pre-processing...                               DONE (in 2s)
INFO: (3 of 6) Context Analyzer training...                            DONE (in 1s)
INFO: (4 of 6) Aligner training...                                     DONE (in 5s)
INFO: (5 of 6) Translation Model training...                           DONE (in 3s)
INFO: (6 of 6) Language Model training...                              DONE (in 13s)

=========== TRAINING SUCCESS ===========

You can now start, stop or check the status of the server with command:
        ./mmt start|stop|status -e test

$ ./mmt start -e test
Starting MMT engine 'test'... OK
Loading models... FAIL

ERROR Unexpected exception:
        Exception('failed to start node, check log file for more details: /home/pangeanic/ModernMT/runtime/test/logs/node.log',)
Traceback (most recent call last):
  File "./mmt", line 846, in <module>
    main()
  File "./mmt", line 792, in main
    actions[command](args)
  File "./mmt", line 245, in main_start
    node.wait('READY')
  File "/home/pangeanic/ModernMT/cli/mmt/cluster.py", line 427, in wait
    raise Exception('failed to start node, check log file for more details: ' + self._log_file)
Exception: failed to start node, check log file for more details: /home/pangeanic/ModernMT/runtime/test/logs/node.log
```

The error is related to the version of cassandra:
```
2018-03-06 16:06:35,116 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
eu.modernmt.engine.BootstrapException: java.io.FileNotFoundException: File '/home/pangeanic/ModernMT/vendor/cassandra-3.11.0/conf/cassandra.yaml' does not exist
        at eu.modernmt.cluster.db.EmbeddedCassandra.start(EmbeddedCassandra.java:36)
        at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:395)
        at eu.modernmt.facade.ModernMT.start(ModernMT.java:53)
        at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:168)
Caused by: java.io.FileNotFoundException: File '/home/pangeanic/ModernMT/vendor/cassandra-3.11.0/conf/cassandra.yaml' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
        at org.apache.commons.io.FileUtils.lineIterator(FileUtils.java:1856)
        at eu.modernmt.cluster.db.EmbeddedCassandra.createConfig(EmbeddedCassandra.java:131)
        at eu.modernmt.cluster.db.EmbeddedCassandra.start(EmbeddedCassandra.java:73)
        at eu.modernmt.cluster.db.EmbeddedCassandra.start(EmbeddedCassandra.java:32)
```

**Comment by davidecaroselli** [comment]
> After compiling/installing, I've got another error related to cassandra. I've needed to change also the pom.xml:
"<cassandra.version>3.11.0</cassandra.version>" to "<cassandra.version>3.11.2</cassandra.version>"

Revert that change. the problem is that MMT is searching for Cassandra in now folder `vendor/cassandra-3.11.2` while, if you followed my advice, you should now have a folder called `vendor/cassandra-3.11.0`

**Comment by alexpangeanic** [comment]
Hi Davide,

Changing the pom.xml and compile to 3.11.2, it has worked the compilation/installation, and also a have created the engines without problems. but I haven't tested everything yet.

BR,
Alex

**Comment by davidecaroselli** [comment]
@alexpangeanic we have just pushed a fix that make MMT use new Cassandra in our `master` branch.
In order to get it run these commands from your ModernMT installation root folder:
```bash
# get latest code
git checkout -- .
git clean -fd
git pull origin master

# get new cassandra version
cd vendor/
rm -rf cassandra-*
./compile
cd ..

# compile ModernMT
cd src
mvn clean install
cd ..
```

Please let me know if this solves the issue.

Thanks!
Davide

**Comment by alexpangeanic** [comment]
Thanks a lot!
