### ISSUE TITLE
Corpus Clean Crash 

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#36]
I was training the news v10 corpus from the WMT task.

I attached the exact sentence that make MMT crash.
[test.zip](https://github.com/ModernMT/MMT/files/83619/test.zip)

And I got this error:
```
./mmt create en fr ../test/ --debug

=========== TRAINING STARTED ===========

ENGINE:  default
CORPORA: /home/ubuntu/test (1 documents)
LANGS:   en > fr

INFO: (1 of 6) Corpora tokenization...                                2016-01-09 10:34:12,207 [DEBUG] - Shell exec: java -cp /home/ubuntu/mmt/build/mmt-0.11.jar -Dmmt.tokenizer.models.path=/home/ubuntu/mmt/opt/tokenizer/models eu.modernmt.cli.TokenizerMain en
2016-01-09 10:34:12,729 [DEBUG] - Shell exec: java -cp /home/ubuntu/mmt/build/mmt-0.11.jar -Dmmt.tokenizer.models.path=/home/ubuntu/mmt/opt/tokenizer/models eu.modernmt.cli.TokenizerMain fr
 DONE (in 1s)
INFO: (2 of 6) Corpora cleaning...                                    2016-01-09 10:34:13,264 [DEBUG] - Shell exec: perl /home/ubuntu/mmt/opt/bin/cleaner-mosesofficial/clean-corpus-n-ratio.perl -ratio 3 /home/ubuntu/mmt/engines/default/temp/tokenizer/news10 en fr /home/ubuntu/mmt/engines/default/temp/cleaner/news10 1 80
 DONE (in 0s)
2016-01-09 10:34:13,281 [ERROR] - Command 'perl /home/ubuntu/mmt/opt/bin/cleaner-mosesofficial/clean-corpus-n-ratio.perl -ratio 3 /home/ubuntu/mmt/engines/default/temp/tokenizer/news10 en fr /home/ubuntu/mmt/engines/default/temp/cleaner/news10 1 80' failed with exit code 255
Traceback (most recent call last):
  File "/home/ubuntu/mmt/scripts/engine.py", line 273, in build
    cleaned_corpora = self._cleaner.batch_clean(tokenized_corpora, cleaner_output)
  File "/home/ubuntu/mmt/scripts/mt/processing.py", line 45, in batch_clean
    [(corpus, ParallelCorpus(corpus.name, dest_folder, corpus.langs), langs) for corpus in corpora])
  File "/home/ubuntu/mmt/scripts/mt/processing.py", line 20, in _pool_exec
    return [job.get() for job in aync_jobs]
  File "/home/ubuntu/mmt/scripts/libs/multithread.py", line 289, in process
    result = self._func(*self._args, **self._kwds)
  File "/home/ubuntu/mmt/scripts/mt/processing.py", line 57, in clean_corpus
    shell.execute(command, stdout=shell.DEVNULL, stderr=shell.DEVNULL)
  File "/home/ubuntu/mmt/scripts/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command 'perl /home/ubuntu/mmt/opt/bin/cleaner-mosesofficial/clean-corpus-n-ratio.perl -ratio 3 /home/ubuntu/mmt/engines/default/temp/tokenizer/news10 en fr /home/ubuntu/mmt/engines/default/temp/cleaner/news10 1 80' failed with exit code 255
Traceback (most recent call last):
  File "./mmt", line 370, in <module>
    main()
  File "./mmt", line 346, in main
    main_create(argv[1:])
  File "./mmt", line 329, in main_create
    engine.build(corpora, debug=args.debug, steps=args.training_steps)
  File "/home/ubuntu/mmt/scripts/engine.py", line 273, in build
    cleaned_corpora = self._cleaner.batch_clean(tokenized_corpora, cleaner_output)
  File "/home/ubuntu/mmt/scripts/mt/processing.py", line 45, in batch_clean
    [(corpus, ParallelCorpus(corpus.name, dest_folder, corpus.langs), langs) for corpus in corpora])
  File "/home/ubuntu/mmt/scripts/mt/processing.py", line 20, in _pool_exec
    return [job.get() for job in aync_jobs]
  File "/home/ubuntu/mmt/scripts/libs/multithread.py", line 289, in process
    result = self._func(*self._args, **self._kwds)
  File "/home/ubuntu/mmt/scripts/mt/processing.py", line 57, in clean_corpus
    shell.execute(command, stdout=shell.DEVNULL, stderr=shell.DEVNULL)
  File "/home/ubuntu/mmt/scripts/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
scripts.libs.shell.ShellError: Command 'perl /home/ubuntu/mmt/opt/bin/cleaner-mosesofficial/clean-corpus-n-ratio.perl -ratio 3 /home/ubuntu/mmt/engines/default/temp/tokenizer/news10 en fr /home/ubuntu/mmt/engines/default/temp/cleaner/news10 1 80' failed with exit code 255
```

**Comment by davidecaroselli** [comment]
Can you also attach the log files inside engines/default/logs?

Il sabato 9 gennaio 2016, Marco Trombetti <notifications@github.com> ha
scritto:

**Comment by davidecaroselli** [comment]
Never mind, I just realized that the entire process took less than 3 seconds :) I'll reproduce the bug.

**Comment by davidecaroselli** [comment]
@marcotrombetti the corpus you've provided is invalid: the EN version has 2 lines, while the FR has only one line. The cleaning script is complaining about that. Can you please check your parallel data to see if same documents have same lengths?

**Comment by marcotrombetti** [comment]
@davidecaroselli I think this is the issue...

There is a broken carriage return that is interpreted in a different way from the tokenizer and cleaner.

Can we filter those so it does not crash?

**Comment by davidecaroselli** [comment]
@marcotrombetti  I've checked the corpus and the fact is that Java already detect the broken carriage return and it fixes it without any problem. The real problem is that the FR version does not have any 'new line' characters at all before the word "Avec": not \n (10), nor \r (13).

The only way we can make it work is to rewrite the Java BufferedReader entirely in a way that it does not tries to fix the broken carriage return. **The result will be a 1-line parallel text**. Is that what we want?

**Comment by davidecaroselli** [comment]
For these kind of data, the best solution appears to be to split lines only on newline char (\n = ASCII 10). I will proceed in this way.
