### ISSUE TITLE
Loading models... FAIL - CassandraDaemon.java:706 - Exception encountered during startup - MMT 2.3

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/MMT#364]
Hi @davidecaroselli ,

Hope it's all well.

I needed MMT 2.3 because it has better handling of Asian languages. So, I trained an engine with the binary version of MMT 2.3 and the training was completed successfully, but it failed to load the engine with this error message:

> Loading models... FAIL
ERROR Unexpected exception:
	Exception('failed to start node, check log file for more details: /opt/orcchinese/runtime/default/logs/node.log',)

Here is the output from the node.log

> 2018-04-25 08:43:46,813 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
eu.modernmt.engine.BootstrapException: java.io.IOException: Unable to start Cassandra process, more details here: /opt/orcchinese/runtime/default/logs/embedded-cassandra.log
	at eu.modernmt.cluster.db.EmbeddedCassandra.start(EmbeddedCassandra.java:36)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:395)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:49)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:168)
Caused by: java.io.IOException: Unable to start Cassandra process, more details here: /opt/orcchinese/runtime/default/logs/embedded-cassandra.log
	at eu.modernmt.cluster.db.EmbeddedCassandra.waitForStartupCompleted(EmbeddedCassandra.java:184)
	at eu.modernmt.cluster.db.EmbeddedCassandra.start(EmbeddedCassandra.java:90)
	at eu.modernmt.cluster.db.EmbeddedCassandra.start(EmbeddedCassandra.java:32)

and this is what I see in embedded-cassandra.log:

> Exception (java.lang.AbstractMethodError) encountered during startup: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientSocketFactory;Ljava/rmi/server/RMIServerSocketFactory;Lsun/misc/ObjectInputFilter;)Ljava/rmi/Remote;
java.lang.AbstractMethodError: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientSocketFactory;Ljava/rmi/server/RMIServerSocketFactory;Lsun/misc/ObjectInputFilter;)Ljava/rmi/Remote;
	at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:150)
	at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:135)
	at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:405)
	at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:104)
	at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:143)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:188)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:689)
ERROR [main] 2018-04-25 08:43:46,200 CassandraDaemon.java:706 - Exception encountered during startup
java.lang.AbstractMethodError: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientSocketFactory;Ljava/rmi/server/RMIServerSocketFactory;Lsun/misc/ObjectInputFilter;)Ljava/rmi/Remote;
	at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:150) ~[na:1.8.0_162]
	at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:135) ~[na:1.8.0_162]
	at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:405) ~[na:1.8.0_162]
	at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:104) ~[apache-cassandra-3.11.0.jar:3.11.0]
	at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:143) [apache-cassandra-3.11.0.jar:3.11.0]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:188) [apache-cassandra-3.11.0.jar:3.11.0]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600) [apache-cassandra-3.11.0.jar:3.11.0]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:689) [apache-cassandra-3.11.0.jar:3.11.0]

I hope you can also fix the cassandra compatibility issue in MMT 2.3 as you did for 2.4. Building from source fails unless you change the version in the pom.xml file and compile file as well to cassandra-3.11.2. cassandra-3.11.0 is missing and the link to it seems to be broken. 

Thanks again for your support!

Kind regards,
Mohamed

**Comment by davidecaroselli** [comment]
Hi @mzeidhassan 

download the binary version of MMT 2.3 from here: [mmt-2.3-ubuntu.tar.gz](https://github.com/ModernMT/MMT/releases/download/v2.3/mmt-2.3-ubuntu.tar.gz).

And then replace your `vendor` folder with the one in the binary release you have just downloaded.

Let me know if this solved the issue.
Davide

**Comment by mzeidhassan** [comment]
Thanks @davidecaroselli for getting back to me.

I am still getting this error


> 2018-04-26 14:10:13,969 INFO  eu.modernmt.cluster.ClusterNode [main] Data stream sync completed in 0.0s
> 2018-04-26 14:10:13,970 INFO  eu.modernmt.cluster.ClusterNode [main] Starting embedded Cassandra process
> 2018-04-26 14:10:16,985 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
> eu.modernmt.engine.BootstrapException: java.io.IOException: Unable to start Cassandra process, more details here: /scratch/mohamed/ModernMT/$
>         at eu.modernmt.cluster.db.EmbeddedCassandra.start(EmbeddedCassandra.java:36)
>         at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:395)
>         at eu.modernmt.facade.ModernMT.start(ModernMT.java:49)
>         at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:168)
> Caused by: java.io.IOException: Unable to start Cassandra process, more details here: /scratch/mohamed/ModernMT/ModernMT/runtime/default/log$
>         at eu.modernmt.cluster.db.EmbeddedCassandra.waitForStartupCompleted(EmbeddedCassandra.java:184)
> 

Still seeing this in embedded-casandra.log

Exception (java.lang.AbstractMethodError) encountered during startup: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/$
java.lang.AbstractMethodError: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientS$
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:150)
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:135)
        at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:405)
        at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:104)
        at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:143)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:188)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:689)
ERROR [main] 2018-04-26 14:10:16,309 CassandraDaemon.java:706 - Exception encountered during startup
java.lang.AbstractMethodError: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientS$
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:150) ~[na:1.8.0_162]
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:135) ~[na:1.8.0_162]
        at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:405) ~[na:1.8.0_162]
        at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:104) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:143) [apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:188) [apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600) [apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:689) [apache-cassandra-3.11.0.jar:3.11.0]

I hope there Thanks @davidecaroselli for getting back to me.

I am still getting this error


> 2018-04-26 14:10:13,969 INFO  eu.modernmt.cluster.ClusterNode [main] Data stream sync completed in 0.0s
> 2018-04-26 14:10:13,970 INFO  eu.modernmt.cluster.ClusterNode [main] Starting embedded Cassandra process
> 2018-04-26 14:10:16,985 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
> eu.modernmt.engine.BootstrapException: java.io.IOException: Unable to start Cassandra process, more details here: /scratch/mohamed/ModernMT/$
>         at eu.modernmt.cluster.db.EmbeddedCassandra.start(EmbeddedCassandra.java:36)
>         at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:395)
>         at eu.modernmt.facade.ModernMT.start(ModernMT.java:49)
>         at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:168)
> Caused by: java.io.IOException: Unable to start Cassandra process, more details here: /scratch/mohamed/ModernMT/ModernMT/runtime/default/log$
>         at eu.modernmt.cluster.db.EmbeddedCassandra.waitForStartupCompleted(EmbeddedCassandra.java:184)
> 

Still seeing this in embedded-casandra.log

Exception (java.lang.AbstractMethodError) encountered during startup: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/$
java.lang.AbstractMethodError: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientS$
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:150)
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:135)
        at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:405)
        at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:104)
        at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:143)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:188)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:689)
ERROR [main] 2018-04-26 14:10:16,309 CassandraDaemon.java:706 - Exception encountered during startup
java.lang.AbstractMethodError: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientS$
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:150) ~[na:1.8.0_162]
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:135) ~[na:1.8.0_162]
        at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:405) ~[na:1.8.0_162]
        at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:104) ~[apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:143) [apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:188) [apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600) [apache-cassandra-3.11.0.jar:3.11.0]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:689) [apache-cassandra-3.11.0.jar:3.11.0]

It seems there is incompatibility issues between different cassandra versions. Although the engine was completed successfully using version 3.11.2. Is there anyway I load this engine successfully? 

Thanks!
Mohamed

**Comment by mzeidhassan** [comment]
Thanks @mehow206 ! This fixed the Cassandra issue indeed. Thank you!

**Comment by davidecaroselli** [comment]
Thanks @mehow206 , I was not aware of this issue with Java. Really appreciated.
