### ISSUE TITLE
Translation Memory: max matching score is 0.5

### ISSUE THREAD

**Issue by patelrajnath** [ModernMT/MMT#368]
Hi,  I was looking into the code of on-the-fly adaptation. So if we have a matching score is equal to 1.0 (a perfect match) it will return the translation from the memory only (corresponding code in **NeuralDecoder** class)-
```
               // if perfect match, return suggestion instead
                if (suggestions[0].score == 1.f) {
                    Word[] words = new Word[suggestions[0].translation.length];
                    for (int i = 0; i < words.length; i++)
                        words[i] = new Word(suggestions[0].translation[i], " ");
                    translation = new Translation(words, text, null);
```
I tried to translate with a segment from the training data which must have a perfect match as the translation memory is built using the same. But the score it (memory matcher) returns is 0.5 instead and it is running 5 epochs of tuning instead of fetching the translation from memory. Is it normal?

**Comment by patelrajnath** [comment]
In the above code, I updated the perfect matching score to 0.5 then it is able to fetch the translation from memory. But the following case again crashes the MMT pipeline.

**If a segment is split into multiple segments and one of them has a perfect match** then it results in the following exception-

```
2018-04-30 17:57:11,865 ERROR eu.modernmt.rest.actions.translation.Translate [qtp1535472351-79] Internal error while executing action Translate
java.lang.NullPointerException
        at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.join(TranslationFacade.java:467)
        at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.merge(TranslationFacade.java:416)
        at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.call(TranslationFacade.java:315)
        at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.call(TranslationFacade.java:1)
        at eu.modernmt.cluster.services.TranslationOperation$TranslationRunnable.run(TranslationOperation.java:45)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at eu.modernmt.cluster.services.PriorityRunnableFuture.run(PriorityRunnableFuture.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at ------ submitted from ------.(Unknown Source)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
        at eu.modernmt.facade.TranslationFacade.get(TranslationFacade.java:113)
        at eu.modernmt.facade.TranslationFacade.get(TranslationFacade.java:93)
        at eu.modernmt.rest.actions.translation.Translate.execute(Translate.java:39)
        at eu.modernmt.rest.actions.translation.Translate.execute(Translate.java:1)
        at eu.modernmt.rest.framework.actions.ObjectAction.getResult(ObjectAction.java:13)
        at eu.modernmt.rest.framework.actions.ObjectAction.getResult(ObjectAction.java:1)
        at eu.modernmt.rest.framework.actions.JSONAction.unsecureExecute(JSONAction.java:51)
        at eu.modernmt.rest.framework.actions.JSONAction.execute(JSONAction.java:22)
        at eu.modernmt.rest.framework.routing.RouterServlet.service(RouterServlet.java:83)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at eu.modernmt.rest.MultipartConfigInjectionHandler.handle(MultipartConfigInjectionHandler.java:49)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at eu.modernmt.rest.MultipartConfigInjectionHandler.handle(MultipartConfigInjectionHandler.java:49)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by davidecaroselli** [comment]
Hi @patelrajnath 

on the 0.5 issue: perfect match in MMT means the exactly same source segment (as you found out) but also 100% match in **context score**. So for the TM the suggestion comes from, you must have a context score from the context vector of exactly 1.0.

Assuming your TM has id 1000, you can translate with context 1.0 with the following command:
```
./mmt translate --context-vector 1000:1 "This is an example"
```

On the second issue, _NullPointerException on sub-segment perfect match_ you are perfectly right, that is a bug, thanks for having found out! I'll working on that asap.

I'll keep you updated.
Thanks

**Comment by davidecaroselli** [comment]
Hi @patelrajnath 

actually I think you have an old version of the code. I did some changes on that part lately that should have solved the issue. In fact the line your log is referring to `TranslationFacade.java:467` does not even exist anymore.

Could you please try to pull from **master** and verify that the issue has been solved also in your case?

Cheers,
Davide

**Comment by patelrajnath** [comment]
@davidecaroselli 
Thanks for the explanation. Where to find this TM id in case I want to try out this. 

About the issue with perfect match on  sub-segment, Now I get the following error-

```
 2018-05-23 16:18:47,781 ERROR eu.modernmt.rest.actions.translation.Translate [qtp562096009-125] Internal error while executing action Translate
eu.modernmt.facade.exceptions.TranslationException: Problem while decoding source sentence
        at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.call(TranslationFacade.java:368)
        at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.call(TranslationFacade.java:279)
        at eu.modernmt.cluster.services.TranslationOperation$TranslationRunnable.run(TranslationOperation.java:45)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at eu.modernmt.cluster.services.PriorityRunnableFuture.run(PriorityRunnableFuture.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at ------ submitted from ------.(Unknown Source)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
        at eu.modernmt.facade.TranslationFacade.get(TranslationFacade.java:117)
        at eu.modernmt.facade.TranslationFacade.get(TranslationFacade.java:97)
        at eu.modernmt.rest.actions.translation.Translate.execute(Translate.java:39)
        at eu.modernmt.rest.actions.translation.Translate.execute(Translate.java:21)
        at eu.modernmt.rest.framework.actions.ObjectAction.getResult(ObjectAction.java:13)
        at eu.modernmt.rest.framework.actions.ObjectAction.getResult(ObjectAction.java:8)
        at eu.modernmt.rest.framework.actions.JSONAction.unsecureExecute(JSONAction.java:51)
        at eu.modernmt.rest.framework.actions.JSONAction.execute(JSONAction.java:22)
        at eu.modernmt.rest.framework.routing.RouterServlet.service(RouterServlet.java:83)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at eu.modernmt.rest.MultipartConfigInjectionHandler.handle(MultipartConfigInjectionHandler.java:49)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:748)
Caused by: eu.modernmt.decoder.neural.NeuralDecoderException: No response from NMT process, request was '{"source":"This may take up to 0 days if you updated your image URLs . It could take longer if you didn 't make any changes to your URLs .","source_language":"en","target_language":"ru","suggestions":[{"source":"This may take up to 0 days if you updated your image URLs . It could take longer if you didn 't make any changes to your URLs .","target":"Если вы изменили URL изображений , проверка займет до четырех дней . Если же URL остались прежними , на проверку может уйти больше времени .","score":0.5}]}'
        at eu.modernmt.decoder.neural.natv.NativeProcess.translate(NativeProcess.java:187)
        at eu.modernmt.decoder.neural.execution.DecoderQueue.translate(DecoderQueue.java:110)
        at eu.modernmt.decoder.neural.NeuralDecoder.translate(NeuralDecoder.java:155)
        at eu.modernmt.decoder.neural.NeuralDecoder.translate(NeuralDecoder.java:127)
        at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.translate(TranslationFacade.java:388)
        at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.translate(TranslationFacade.java:376)
        at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.call(TranslationFacade.java:315)
        at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.call(TranslationFacade.java:279)
        at eu.modernmt.cluster.services.TranslationOperation$TranslationRunnable.run(TranslationOperation.java:45)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at eu.modernmt.cluster.services.PriorityRunnableFuture.run(PriorityRunnableFuture.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
```
I think it has to do with the fact that the perfect matched segment will not have the alignment when you try to **merge them**. We check the null alignment (line no 317 in TranslationFacade) but after the merge process (line no 323). So if we update the alignment in the following method of TranslationFacade class-

```
        private Translation[] translate(Sentence[] sentences, Engine engine) throws DecoderException, AlignerException {
            Translation[] translations = new Translation[sentences.length];

			for (int i = 0; i < sentences.length; i++) {
				Translation translation = this.translate(sentences[i], engine);
				// Alignment
				if (!translation.hasAlignment()) {
					Aligner aligner = engine.getAligner();
					Alignment alignment = aligner.getAlignment(direction, sentences[i], translation);
					translation.setWordAlignment(alignment);
				}
				translations[i] = translation;
			}
            return translations;
        }
```
This should be fine.

**Comment by patelrajnath** [comment]
I could create a PR for the fix if you would add me (patelrajnath@gmail.com) to the contributors' list.

**Comment by davidecaroselli** [comment]
Hi @patelrajnath 

thank you for your PR, really appreciated! I just merged it into branch `bugfix/issue-368`. I moved your code at sentence-piece level so that the whole check-and-realignment is made only once always.

Thank you again for the proposed solution: an you please check if the branch `bugfix/issue-368` finally works in your case? If so, I'm going to merge it into master.

Davide

**Comment by patelrajnath** [comment]
It works fine now.
