### ISSUE TITLE
cannot start MMT after training...

### ISSUE THREAD

**Issue by philippehenri** [ModernMT/MMT#402]
Hello

I did a training with MMT 3.0, now i want to start it:
~/mmt$ ./mmt start -e wsenfr3 -p 8045 --cluster-port 5016 --datastream-port 9092 --db-port 9042
Starting MMT engine 'wsenfr3'... FAIL

ERROR Unexpected exception: failed to start node, check log file for more details: /home/ubuntu/mmt/runtime/wsenfr3/logs/node.log
Traceback (most recent call last):
  File "./mmt", line 610, in <module>
    main()
  File "./mmt", line 556, in main
    actions[command](args)
  File "./mmt", line 191, in main_start
    log_file=args.log_file)
  File "/home/ubuntu/mmt/cli/mmt/cluster.py", line 314, in start
    raise Exception('failed to start node, check log file for more details: %s' % self._log_file)
Exception: failed to start node, check log file for more details: /home/ubuntu/mmt/runtime/wsenfr3/logs/node.log
ubuntu@b7ca1778b964:~/mmt$

and in gc.log (the only log file), i can read:

cat gc.log
OpenJDK 64-Bit Server VM (25.181-b13) for linux-amd64 JRE (1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13), built on Jul 30 2018 21:06:27 by "buildd" with gcc 5.4.0 20160609
Memory: 4k page, physical 65822428k(65022132k free), swap 33521660k(33521660k free)
CommandLine flags: -XX:+CMSClassUnloadingEnabled -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:+CMSScavengeBeforeRemark -XX:ErrorFile=/home/ubuntu/mmt/runtime/wsenfr3/logs/hs_err_pid%p.log -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/ubuntu/mmt/runtime/wsenfr3/logs -XX:InitialHeapSize=16106127360 -XX:MaxHeapSize=16106127360 -XX:MaxNewSize=697933824 -XX:MaxTenuringThreshold=6 -XX:NewSize=697933824 -XX:OldPLABSize=16 -XX:OldSize=1395867648 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+ScavengeBeforeFullGC -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseParNewGC
Heap
 par new generation   total 613440K, used 32721K [0x0000000400000000, 0x0000000429990000, 0x0000000429990000)
  eden space 545344K,   6% used [0x0000000400000000, 0x0000000401ff4420, 0x0000000421490000)
  from space 68096K,   0% used [0x0000000421490000, 0x0000000421490000, 0x0000000425710000)
  to   space 68096K,   0% used [0x0000000425710000, 0x0000000425710000, 0x0000000429990000)
 concurrent mark-sweep generation total 15047104K, used 0K [0x0000000429990000, 0x00000007c0000000, 0x00000007c0000000)
 Metaspace       used 2802K, capacity 4600K, committed 4864K, reserved 1056768K
  class space    used 298K, capacity 424K, committed 512K, reserved 1048576K

Can someone help please?
thanks
Phil

**Comment by philippehenri** [comment]
ps: i just noted that without params, it starts ok: ./mmt start -e wsfren3 

but then how i can run two engines on the same machine?

**Comment by nicolabertoldi** [comment]
@philippehenri 
Regarding the problem you had, could you please look into this log
/home/ubuntu/mmt/runtime/wsenfr3/logs/node.log
Is there any error, in the loading phase?

Actually, you can start two engines, paying attention that;
- they use different ports
- they use different GPUs (or the GPUs are powerful enough to handle with models).

**Comment by philippehenri** [comment]
there is no node.log, only the gc.log i pasted...

ps:yes i know i could start 2 engines before with the -p... params (version MMT 2.5)

**Comment by philippehenri** [comment]
same problem, no node.log...

./mmt start -v 2 -e wsenfr3 -p 8046 --cluster-port 5017 --datastream-port 9093 --db-port 9043
Starting MMT engine 'wsenfr3'... FAIL

ERROR Unexpected exception: failed to start node, check log file for more details: /home/ubuntu/mmt/runtime/wsenfr3/logs/node.log
Traceback (most recent call last):
  File "./mmt", line 610, in <module>
    main()
  File "./mmt", line 556, in main
    actions[command](args)
  File "./mmt", line 191, in main_start
    log_file=args.log_file)
  File "/home/ubuntu/mmt/cli/mmt/cluster.py", line 314, in start
    raise Exception('failed to start node, check log file for more details: %s' % self._log_file)
Exception: failed to start node, check log file for more details: /home/ubuntu/mmt/runtime/wsenfr3/logs/node.log

**Comment by philippehenri** [comment]
additional info !: if tried to start with one parameter at a time, they all start ok **except* the one with all params including the last one (db-port ): 

all ok:
./mmt start -v 2 -e wsenfr3 -p 8046 
./mmt start -v 2 -e wsenfr3 -p 8046 --cluster-port 5017 
./mmt start -v 2 -e wsenfr3 -p 8046 --cluster-port 5017 --datastream-port 9093 

NOT OK:
./mmt start -v 2 -e wsenfr3 -p 8046 --cluster-port 5017 --datastream-port 9093 --db-port 9043

**Comment by nicolabertoldi** [comment]
Actually you spot a minor bug.
I have just pushed the fix.

Please, update the source code and recompile, and everything will work fine.

After your double-check, if no more problem,
please feel free to close the issue.

**Comment by nicolabertoldi** [comment]
@philippehenri 
thank you for spotting the "cryptography" issue
I will open a new issue for it
