### ISSUE TITLE
Cannot specify ports

### ISSUE THREAD

**Issue by LoekvanKooten** [ModernMT/MMT#404]
`./mmt start -e japdut -p 8046 --cluster-port 5017 --datastream-port 9093 --db-port 9043`

gives

`Starting MMT engine 'japdut'... FAIL

ERROR Unexpected exception: failed to start node, check log file for more details: /home/loek/mmt3/runtime/japdut/logs/node.log
Traceback (most recent call last):
  File "./mmt", line 610, in <module>
    main()
  File "./mmt", line 556, in main
    actions[command](args)
  File "./mmt", line 191, in main_start
    log_file=args.log_file)
  File "/home/loek/mmt3/cli/mmt/cluster.py", line 314, in start
    raise Exception('failed to start node, check log file for more details: %s' % self._log_file)
Exception: failed to start node, check log file for more details: /home/loek/mmt3/runtime/japdut/logs/node.log`

The log says:

`2018-10-02 08:32:09,357 INFO  eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
2018-10-02 08:32:09,901 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined the cluster in 0.392s
2018-10-02 08:32:09,903 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2018-10-02 08:32:09,917 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loading FastAlign models
2018-10-02 08:32:09,964 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loaded 1 FastAlign models in 0s
2018-10-02 08:32:10,110 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-1] Starting native decoder process
2018-10-02 08:32:47,221 INFO  eu.modernmt.decoder.neural.execution.impl.DecoderQueueImpl [pool-7-thread-1] Native decoder process started in 37s
2018-10-02 08:32:47,221 INFO  eu.modernmt.cluster.ClusterNode [main] Model loaded in 37.318s
2018-10-02 08:32:47,221 INFO  eu.modernmt.cluster.ClusterNode [main] Starting embedded Kafka process
2018-10-02 08:32:50,244 INFO  eu.modernmt.cluster.ClusterNode [main] Embedded Kafka started in 3.023s
2018-10-02 08:32:50,249 INFO  eu.modernmt.cluster.ClusterNode [main] Connecting to dataManager...
2018-10-02 08:32:50,510 INFO  eu.modernmt.cluster.kafka.KafkaDataManager [Thread-5] Channel 'memory-upload-stream' seek to position 0
2018-10-02 08:32:50,511 INFO  eu.modernmt.cluster.kafka.KafkaDataManager [Thread-5] Channel 'contributions-stream' seek to position 4518
2018-10-02 08:32:50,511 INFO  eu.modernmt.cluster.ClusterNode [main] Connected to the dataManager in 0.262s
2018-10-02 08:32:50,512 INFO  eu.modernmt.cluster.ClusterNode [main] Data stream sync running in background, force single node cluster start
2018-10-02 08:32:50,512 INFO  eu.modernmt.cluster.ClusterNode [main] Starting embedded Cassandra process
2018-10-02 08:32:54,519 INFO  eu.modernmt.cluster.ClusterNode [main] Embedded Cassandra started in 4.007s
2018-10-02 08:32:54,980 INFO  eu.modernmt.cluster.ClusterNode [main] Node started in 45.63s
2018-10-02 08:33:02,136 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting API interface...
2018-10-02 08:33:02,140 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] API interface halted
2018-10-02 08:33:02,141 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting Translation Service...
2018-10-02 08:33:02,141 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Translation Service halted
2018-10-02 08:33:02,141 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting Engine...
2018-10-02 08:33:02,213 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Engine halted
2018-10-02 08:33:02,213 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting component "CassandraDatabase"...
2018-10-02 08:33:04,431 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Component "CassandraDatabase" halted
2018-10-02 08:33:04,431 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting component "KafkaDataManager"...
2018-10-02 08:33:04,449 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Component "KafkaDataManager" halted
2018-10-02 08:33:04,449 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting service "EmbeddedKafka"...
2018-10-02 08:33:08,618 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Service "EmbeddedKafka" halted
2018-10-02 08:33:08,619 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting service "EmbeddedCassandra"...
2018-10-02 08:33:11,514 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Service "EmbeddedCassandra" halted
2018-10-02 08:33:11,518 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] System halted in 9s`

**Comment by nicolabertoldi** [comment]
We had a similar problem described in #402, and already solved in .
Which commit are you using? the latest

if this update does not solve the problem,
could you please report the content of
runtime/japdut/cassandra/cassandra.yaml

**Comment by LoekvanKooten** [comment]
Okay, very stupid question: what's the easiest way to update my files? I'm using the barebone MMT (no dockers) in tensorflow.

**Comment by LoekvanKooten** [comment]
Never mind! Re-installing from source did the trick. It works now. Thank you for your help!

**Comment by nicolabertoldi** [comment]
good to know

I close the issue, but please feel free to re-open in case you need more help about this issue.
