### ISSUE TITLE
MMT 3.2 training crash

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#408]
Looking at the code, I don't understand what is going wrong. 
Here is the end of LOG file:
```
...
2018-10-24 13:54:04,166 [INFO] - Training step "train_aligner" completed in 2h 7m 59s
2018-10-24 13:54:04,167 [INFO] - Training step "write_config" (4/7) started
2018-10-24 13:54:04,167 [INFO] - Training step "write_config" completed in 0s
2018-10-24 13:54:04,167 [INFO] - Training step "prepare_data" (4/7) started
2018-10-24 13:54:04,168 [DEBUG] - t2t-datagen --t2t_usr_dir /home/lm-dev8/MMT32/build/lib/t2t --data_dir=/home/lm-dev8/MMT32/runtime/FREN_New/tmp/training/neural_train_data/data --tmp_dir=/home/lm-dev8/MMT32/runtime/FREN_New/tmp/training/neural_train_data/tmp --problem=translate_mmt
2018-10-24 13:54:04,350 [ERROR] - Unexpected exception
Traceback (most recent call last):
  File "/home/lm-dev8/MMT32/cli/mmt/engine.py", line 629, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/lm-dev8/MMT32/cli/mmt/engine.py", line 428, in __call__
    self._f(*args, **kwargs)
  File "/home/lm-dev8/MMT32/cli/mmt/engine.py", line 760, in _prepare_data
    log=log, bpe_symbols=self._bpe_symbols)
  File "/home/lm-dev8/MMT32/cli/mmt/engine.py", line 153, in prepare_data
    osutils.shell_exec(command, stdout=log, stderr=log, env=env)
  File "/home/lm-dev8/MMT32/cli/libs/osutils.py", line 41, in shell_exec
    shell=(True if isinstance(cmd, basestring) else False), env=env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by EtienneAb3d** [comment]
It lacks` t2t-datagen`? How to get it?

**Comment by nicolabertoldi** [comment]
t2t-datagen together with t2t-trainer are installed during the installation process
with the following two commands
pip install tensorflow-gpu==1.8.0
pip install tensor2tensor==1.6.3

Have you run the full installation process?
In theory, t2t-datagen should be installed in a subdirectory of the directory where the command pip is.

**Comment by EtienneAb3d** [comment]
I exactly followed the install instruction. It was installed here:
`~.local/bin`

**Comment by nicolabertoldi** [comment]
which is the content of "~/.local/bin" and of "~/.local/lib"?

**Comment by nicolabertoldi** [comment]
probably you do not have 
~/.local/bin
in the PATH environment

Could you please try add?

**Comment by EtienneAb3d** [comment]
I'm just trying a test having added it to the PATH in may training launch shell.

Contents:
```
lm-dev8@dev8:~$ ls .local/lib/
python2.7
lm-dev8@dev8:~$ ls .local/bin
chardetect        flask         gunicorn         markdown_py  pyrsa-decrypt  pyrsa-priv2pub  saved_model_cli  t2t-datagen   t2t-insights-server  t2t-trainer        toco
easy_install      freeze_graph  gunicorn_paster  pasteurize   pyrsa-encrypt  pyrsa-sign      t2t-avg-all      t2t-decoder   t2t-make-tf-configs  t2t-translate-all  toco_from_protos
easy_install-2.7  futurize      isympy           pbr          pyrsa-keygen   pyrsa-verify    t2t-bleu         t2t-exporter  t2t-query-server     tensorboard        wheel
```

**Comment by nicolabertoldi** [comment]
I suppose that the correct setting of PATH solves your problem.

If so, could you please close the issue?

**Comment by EtienneAb3d** [comment]
Do you know why I was obliged to set this PATH myself? Didn't you have the same problem? Why not adding a line about this in your install instructions?

Otherwise, yes, it seems to work.

I still have some troubles with the training. Certainly because of something that didn't run properly in my installation, made by fast copy/paste of your instructions. For example, here, I didn't see that there is a version number I have to change. My fast copy/paste didn't work, and the error was a bit lost in full the LOG screen:

`sudo apt-key add /var/cuda-repo-<version>/7fa2af80.pub
`

**Comment by EtienneAb3d** [comment]
I don't know why I got an installation in `~/.local/bin`. Since I do not succeed in running properly tensorboard, I tried this: 

1. remove this whole folder `~/.local`
2. re-install Tensorflow and Tensor2Tensor, being myslelf located in my home dir, and using sudo for each command

I no more have this installation in `~/.local/bin`.

**Comment by nicolabertoldi** [comment]
I suppose you have solved this issue.
I close the issue, but please feel free to re-open it if you need it.
