### ISSUE TITLE
Translation issue - ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by robertBrnnn** [ModernMT/MMT#422]
Hi @davidecaroselli @nicolabertoldi 

We've been consistently seeing an issue with translation against our ZH MMT3.0 engine. I've tried to gather as much info as I can for you.

The corresponding lines in node.log is:
`2018-11-20 11:21:46,986 ERROR eu.modernmt.api.actions.translation.Translate [qtp1070319462-308] Internal error while executing action Translate
java.lang.ArrayIndexOutOfBoundsException: 15
	at eu.modernmt.processing.WordTextGuessingProcessor.call(WordTextGuessingProcessor.java:28)
	at eu.modernmt.processing.WordTextGuessingProcessor.call(WordTextGuessingProcessor.java:13)
	at eu.modernmt.processing.ProcessingPipeline.call(ProcessingPipeline.java:32)
	at eu.modernmt.processing.VoidProcessingPipeline.call(VoidProcessingPipeline.java:22)
	at eu.modernmt.processing.VoidProcessingPipeline.call(VoidProcessingPipeline.java:9)
	at eu.modernmt.processing.ProcessingPipeline.call(ProcessingPipeline.java:20)
	at eu.modernmt.processing.VoidProcessingPipeline.call(VoidProcessingPipeline.java:16)
	at eu.modernmt.processing.VoidProcessingPipeline.call(VoidProcessingPipeline.java:9)
	at eu.modernmt.processing.concurrent.PipelineExecutor.process(PipelineExecutor.java:29)
	at eu.modernmt.processing.Postprocessor.process(Postprocessor.java:45)
	at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.call(TranslationFacade.java:254)
	at eu.modernmt.facade.TranslationFacade$TranslationTaskImpl.call(TranslationFacade.java:214)
	at eu.modernmt.cluster.services.TranslationOperation$TranslationRunnable.run(TranslationOperation.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at eu.modernmt.cluster.services.PriorityRunnableFuture.run(PriorityRunnableFuture.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at eu.modernmt.facade.TranslationFacade.get(TranslationFacade.java:83)
	at eu.modernmt.facade.TranslationFacade.get(TranslationFacade.java:69)
	at eu.modernmt.api.actions.translation.Translate.execute(Translate.java:44)
	at eu.modernmt.api.actions.translation.Translate.execute(Translate.java:26)
	at eu.modernmt.api.framework.actions.ObjectAction.getResult(ObjectAction.java:13)
	at eu.modernmt.api.framework.actions.ObjectAction.getResult(ObjectAction.java:8)
	at eu.modernmt.api.framework.actions.JSONAction.unsecureExecute(JSONAction.java:51)
	at eu.modernmt.api.framework.actions.JSONAction.execute(JSONAction.java:22)
	at eu.modernmt.api.framework.routing.RouterServlet.service(RouterServlet.java:83)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at eu.modernmt.api.MultipartConfigInjectionHandler.handle(MultipartConfigInjectionHandler.java:49)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
2018-11-20 11:21:46,987 INFO  eu.modernmt.api.ApiServer.Router [qtp1070319462-308] "GET /translate?source=en&target=zh&q=From%20the%20secure%20shell%2C%20unpack%20the%20tarball%20and%20install%20the%20${DNT1}" 500 385`

The response from the REST API is:
`{"status":500,"error":{"type":"ArrayIndexOutOfBoundsException","message":"15"}}`

I've been able to reproduce this consistently for the same string against the ZH engine
Do you have any idea what is causing this issue?

Thanks,
Rob

**Comment by nicolabertoldi** [comment]
Hi @robertBrnnn ,

It is very likely that this issue regards the DNT tag as well, and it is related with the previous ones #414 and #420.
The issue has been solved in the latest commit.

If I am right, this problem does not occur if you do not have DNT tags in the input, or if you work with other languages different from CJK?
Could you confirm this?

May I also ask you to retry with the new commit?

Nicola

**Comment by robertBrnnn** [comment]
Hi @nicolabertoldi 
Yes you're correct, it is only occurring when the text has DNT tokens, and is a CJK language.

I will retry with the latest commit as soon as possible, and get back to you when I have tested this.

Thanks a lot for your support,
Rob

**Comment by robertBrnnn** [comment]
Hi @nicolabertoldi 

Apologies for the delay in getting back to you.
We haven't encountered this issue with latest version of MMT, so I'm going to close this issue.

May thanks for your continuous support,
Rob
