### ISSUE TITLE
Training parameters

### ISSUE THREAD

**Issue by sdlmw** [ModernMT/MMT#429]
Hello！

I'm trying the latest version of 3.2.3.  But I'm meeting a strange problem.  

1.   ./mmt create  \
  --learning-rate-decay-start-at 1000000 \
  --learning-rate-decay-steps 50000 \
  --learning-rate-decay 0.8 \
  --validation-steps 50000 \
  --checkpoint-steps 50000 \
  -e FREN_New --neural  en zh\
 /MT-work/Corpus/180514\
  --gpus 0

output：
usage: mmt create [-h] [-e ENGINE] [-d] [-s STEPS [STEPS ...]] [-r] [-y]
                  [--no-split] [--validation-corpora VALIDATION_CORPORA]
                  [--batch-size BATCH_SIZE] [--train-steps N_TRAIN_STEPS]
                  [--eval-steps EVAL_FREQ] [--hparams HPARAMS]
                  [--bpe BPE_SYMBOLS] [--gpus GPUS [GPUS ...]]
                  SOURCE_LANGUAGE TARGET_LANGUAGE CORPORA [CORPORA ...]
mmt create: error: unrecognized arguments: --learning-rate-decay-start-at --learning-rate-decay-steps --learning-rate-decay --validation-steps 50000 --checkpoint-steps 50000 --neural en zh /MT-work/180514

2.  ./mmt create en zh /MT-work/Corpus/180514  -e test --neural

output:
usage: mmt create [-h] [-e ENGINE] [-d] [-s STEPS [STEPS ...]] [-r] [-y]
                  [--no-split] [--validation-corpora VALIDATION_CORPORA]
                  [--batch-size BATCH_SIZE] [--train-steps N_TRAIN_STEPS]
                  [--eval-steps EVAL_FREQ] [--hparams HPARAMS]
                  [--bpe BPE_SYMBOLS] [--gpus GPUS [GPUS ...]]
                  SOURCE_LANGUAGE TARGET_LANGUAGE CORPORA [CORPORA ...]
mmt create: error: unrecognized arguments: --neural

May I ask if the--neural parameter is canceled?

thank you!

**Comment by nicolabertoldi** [comment]
Since version 3.x, ModernMT supports neural framework only.
Hence, the parameter ``--neural`` is no more valid.

The help of the creation command
```./mmt create --help```
shows all legal parameters for the creation of an engine.

**Comment by sdlmw** [comment]
Hi @nicolabertoldi ,

ok， Is there a total of 6 steps in the version training step after 3.X?

And, i have another question.   I can train an engine normally, but can't run the engine.  This is the 2.5 version of the engine.  Will throw such a mistake：

`mingwei@VN-MT:~/MMT_3.2.3$ ./mmt start -e en-US_zh-CN
Starting MMT engine 'en-US_zh-CN'... OK
Loading models... FAIL

ERROR Unexpected exception: failed to start node, check log file for more details: /home/mingwei/MMT_3.2.3/runtime/en-US_zh-CN/logs/node.log
Traceback (most recent call last):
  File "./mmt", line 610, in <module>
    main()
  File "./mmt", line 556, in main
    actions[command](args)
  File "./mmt", line 196, in main_start
    node.wait('RUNNING')
  File "/home/mingwei/MMT_3.2.3/cli/mmt/cluster.py", line 354, in wait
    raise Exception('failed to start node, check log file for more details: ' + self._log_file)
Exception: failed to start node, check log file for more details: /home/mingwei/MMT_3.2.3/runtime/en-US_zh-CN/logs/node.log
`
 /home/mingwei/MMT_3.2.3/runtime/en-US_zh-CN/logs/node.log:
`2018-12-11 09:46:19,120 INFO  eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
2018-12-11 09:46:20,414 INFO  eu.modernmt.cluster.ClusterNode [main] Node joined cluster of 1 members in 0.934s
2018-12-11 09:46:20,524 INFO  eu.modernmt.cluster.ClusterNode [main] Model loading started
2018-12-11 09:46:20,549 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loading FastAlign models
2018-12-11 09:46:20,747 INFO  eu.modernmt.aligner.fastalign.FastAlign [main] Loaded 1 FastAlign models in 0s
2018-12-11 09:46:21,101 ERROR eu.modernmt.cli.ClusterNodeMain [main] Failed to start node
eu.modernmt.engine.BootstrapException: Failed to instantiate context analyzer
	at eu.modernmt.engine.Engine.load(Engine.java:90)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:278)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:54)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:182)
Caused by: java.io.IOException: org.sqlite.SQLiteException: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database)
	at eu.modernmt.context.lucene.storage.BucketRegistry.<init>(BucketRegistry.java:36)
	at eu.modernmt.context.lucene.storage.CorporaStorage.<init>(CorporaStorage.java:29)
	at eu.modernmt.context.lucene.storage.CorporaStorage.<init>(CorporaStorage.java:22)
	at eu.modernmt.context.lucene.LuceneAnalyzer.<init>(LuceneAnalyzer.java:44)
	at eu.modernmt.context.lucene.LuceneAnalyzer.<init>(LuceneAnalyzer.java:40)
	at eu.modernmt.engine.Engine.load(Engine.java:88)
	... 3 more
Caused by: org.sqlite.SQLiteException: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
	at org.sqlite.core.NativeDB._exec(NativeDB.java:87)
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:116)
	at eu.modernmt.context.lucene.storage.BucketRegistry.createDatabaseIfNotExists(BucketRegistry.java:51)
	at eu.modernmt.context.lucene.storage.BucketRegistry.<init>(BucketRegistry.java:34)
	... 8 more
2018-12-11 09:46:21,103 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
eu.modernmt.engine.BootstrapException: Failed to instantiate context analyzer
	at eu.modernmt.engine.Engine.load(Engine.java:90)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:278)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:54)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:182)
Caused by: java.io.IOException: org.sqlite.SQLiteException: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database)
	at eu.modernmt.context.lucene.storage.BucketRegistry.<init>(BucketRegistry.java:36)
	at eu.modernmt.context.lucene.storage.CorporaStorage.<init>(CorporaStorage.java:29)
	at eu.modernmt.context.lucene.storage.CorporaStorage.<init>(CorporaStorage.java:22)
	at eu.modernmt.context.lucene.LuceneAnalyzer.<init>(LuceneAnalyzer.java:44)
	at eu.modernmt.context.lucene.LuceneAnalyzer.<init>(LuceneAnalyzer.java:40)
	at eu.modernmt.engine.Engine.load(Engine.java:88)
	... 3 more
Caused by: org.sqlite.SQLiteException: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
	at org.sqlite.core.NativeDB._exec(NativeDB.java:87)
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:116)
	at eu.modernmt.context.lucene.storage.BucketRegistry.createDatabaseIfNotExists(BucketRegistry.java:51)
	at eu.modernmt.context.lucene.storage.BucketRegistry.<init>(BucketRegistry.java:34)
	... 8 more
2018-12-11 09:46:21,628 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting API interface...
2018-12-11 09:46:21,636 INFO  eu.modernmt.cluster.ClusterNode [ShutdownThread] API interface halted
2018-12-11 09:46:21,636 FATAL eu.modernmt.facade.ModernMT [ShutdownThread] Unexpected exception thrown by thread [ShutdownThread]
java.lang.IllegalStateException: ClusterNode not ready. Call bootstrap() to initialize the member.
	at eu.modernmt.cluster.ClusterNode.getEngine(ClusterNode.java:91)
	at eu.modernmt.cluster.ShutdownThread.run(ShutdownThread.java:36)
`

I don't know why this is happening, Environment tools are installed exactly as tutorials. Tool version number is consistent. So， Can you tell me what the problem is?

thanks

**Comment by sdlmw** [comment]
Hi @nicolabertoldi ，

ok， Is there a total of 6 steps in the version training step after 3.X?

And, i have another question. I can train an engine normally, but can't run the engine. This is the 2.5 version of the engine. Will throw such a mistake：

`mingwei@VN-MT:~/MMT_3.2.3$ ./mmt start -e en-US_zh-CN
Starting MMT engine 'en-US_zh-CN'... OK
Loading models... FAIL

ERROR Unexpected exception: failed to start node, check log file for more details: /home/mingwei/MMT_3.2.3/runtime/en-US_zh-CN/logs/node.log
Traceback (most recent call last):
File "./mmt", line 610, in 
main()
File "./mmt", line 556, in main
actionscommand
File "./mmt", line 196, in main_start
node.wait('RUNNING')
File "/home/mingwei/MMT_3.2.3/cli/mmt/cluster.py", line 354, in wait
raise Exception('failed to start node, check log file for more details: ' + self._log_file)
Exception: failed to start node, check log file for more details: `/home/mingwei/MMT_3.2.3/runtime/en-US_zh-CN/logs/node.log`

/home/mingwei/MMT_3.2.3/runtime/en-US_zh-CN/logs/node.log:
`
2018-12-11 09:46:19,120 INFO eu.modernmt.cluster.ClusterNode [main] Node is joining the cluster
2018-12-11 09:46:20,414 INFO eu.modernmt.cluster.ClusterNode [main] Node joined cluster of 1 members in 0.934s
2018-12-11 09:46:20,524 INFO eu.modernmt.cluster.ClusterNode [main] Model loading started
2018-12-11 09:46:20,549 INFO eu.modernmt.aligner.fastalign.FastAlign [main] Loading FastAlign models
2018-12-11 09:46:20,747 INFO eu.modernmt.aligner.fastalign.FastAlign [main] Loaded 1 FastAlign models in 0s
2018-12-11 09:46:21,101 ERROR eu.modernmt.cli.ClusterNodeMain [main] Failed to start node
eu.modernmt.engine.BootstrapException: Failed to instantiate context analyzer
at eu.modernmt.engine.Engine.load(Engine.java:90)
at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:278)
at eu.modernmt.facade.ModernMT.start(ModernMT.java:54)
at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:182)
Caused by: java.io.IOException: org.sqlite.SQLiteException: [SQLITE_NOTADB] File opened that is not a database file (file is not a database)
at eu.modernmt.context.lucene.storage.BucketRegistry.(BucketRegistry.java:36)
at eu.modernmt.context.lucene.storage.CorporaStorage.(CorporaStorage.java:29)
at eu.modernmt.context.lucene.storage.CorporaStorage.(CorporaStorage.java:22)
at eu.modernmt.context.lucene.LuceneAnalyzer.(LuceneAnalyzer.java:44)
at eu.modernmt.context.lucene.LuceneAnalyzer.(LuceneAnalyzer.java:40)
at eu.modernmt.engine.Engine.load(Engine.java:88)
... 3 more
Caused by: org.sqlite.SQLiteException: [SQLITE_NOTADB] File opened that is not a database file (file is not a database)
at org.sqlite.core.DB.newSQLException(DB.java:909)
at org.sqlite.core.DB.newSQLException(DB.java:921)
at org.sqlite.core.DB.throwex(DB.java:886)
at org.sqlite.core.NativeDB._exec_utf8(Native Method)
at org.sqlite.core.NativeDB._exec(NativeDB.java:87)
at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:116)
at eu.modernmt.context.lucene.storage.BucketRegistry.createDatabaseIfNotExists(BucketRegistry.java:51)
at eu.modernmt.context.lucene.storage.BucketRegistry.(BucketRegistry.java:34)
... 8 more
2018-12-11 09:46:21,103 FATAL eu.modernmt.facade.ModernMT [main] Unexpected exception thrown by thread [main]
eu.modernmt.engine.BootstrapException: Failed to instantiate context analyzer
at eu.modernmt.engine.Engine.load(Engine.java:90)
at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:278)
at eu.modernmt.facade.ModernMT.start(ModernMT.java:54)
at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:182)
Caused by: java.io.IOException: org.sqlite.SQLiteException: [SQLITE_NOTADB] File opened that is not a database file (file is not a database)
at eu.modernmt.context.lucene.storage.BucketRegistry.(BucketRegistry.java:36)
at eu.modernmt.context.lucene.storage.CorporaStorage.(CorporaStorage.java:29)
at eu.modernmt.context.lucene.storage.CorporaStorage.(CorporaStorage.java:22)
at eu.modernmt.context.lucene.LuceneAnalyzer.(LuceneAnalyzer.java:44)
at eu.modernmt.context.lucene.LuceneAnalyzer.(LuceneAnalyzer.java:40)
at eu.modernmt.engine.Engine.load(Engine.java:88)
... 3 more
Caused by: org.sqlite.SQLiteException: [SQLITE_NOTADB] File opened that is not a database file (file is not a database)
at org.sqlite.core.DB.newSQLException(DB.java:909)
at org.sqlite.core.DB.newSQLException(DB.java:921)
at org.sqlite.core.DB.throwex(DB.java:886)
at org.sqlite.core.NativeDB._exec_utf8(Native Method)
at org.sqlite.core.NativeDB._exec(NativeDB.java:87)
at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:116)
at eu.modernmt.context.lucene.storage.BucketRegistry.createDatabaseIfNotExists(BucketRegistry.java:51)
at eu.modernmt.context.lucene.storage.BucketRegistry.(BucketRegistry.java:34)
... 8 more
2018-12-11 09:46:21,628 INFO eu.modernmt.cluster.ClusterNode [ShutdownThread] Halting API interface...
2018-12-11 09:46:21,636 INFO eu.modernmt.cluster.ClusterNode [ShutdownThread] API interface halted
2018-12-11 09:46:21,636 FATAL eu.modernmt.facade.ModernMT [ShutdownThread] Unexpected exception thrown by thread [ShutdownThread]
java.lang.IllegalStateException: ClusterNode not ready. Call bootstrap() to initialize the member.
at eu.modernmt.cluster.ClusterNode.getEngine(ClusterNode.java:91)
at eu.modernmt.cluster.ShutdownThread.run(ShutdownThread.java:36)
`

I don't know why this is happening, Environment tools are installed exactly as tutorials. Tool version number is consistent. So， Can you tell me what the problem is?

**Comment by nicolabertoldi** [comment]
Hi @sdlmw 
v3.2.3 has 6 training steps

I I well understood, you are using an engine trained with 2.5 with the v3.2.3.
This is not possible.

**Comment by sdlmw** [comment]
Hi @nicolabertoldi 

I just retry,

![image](https://user-images.githubusercontent.com/13164077/49788886-803ff700-fd65-11e8-976c-eb81cb768258.png)
I found v3.2.3 has seven (6) training steps.

Command: ./mmt create en de /data/corpus -e default_engine_181211
is it right?

thank you!

**Comment by nicolabertoldi** [comment]
@sdlmw 
v3.2.3 has 6 (six) training steps.

The command you mentioned is correct
```
./mmt create en de /data/corpus -e default_engine_181211
```

Until you successfully complete a training, I can suggest you to add these two options
```
--debug --resume 
```
so that you can debug the training steps and resume the training (if something fails).


If everything goes fine and you successfully train your engine as expected,
we would kindly ask you to close the issue.

Otherwise, feel free to ask us further support.

**Comment by sdlmw** [comment]
@nicolabertoldi 
Thank you for your support.

I have one more question. `--train_steps`  Is that a required parameter?    Or get the best training results within a certain value.

**Comment by sdlmw** [comment]
@davidecaroselli 

Thank you for your explanation. #396 This issue perfectly explains my problem.
