### ISSUE TITLE
Can't resume a training

### ISSUE THREAD

**Issue by EtienneAb3d** [ModernMT/MMT#439]
Hi,
When trying to resume, I get this error: 
```
Traceback (most recent call last):
  File "/home/lm-dev8/MMT323/ModernMT/cli/mmt/engine.py", line 632, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/lm-dev8/MMT323/ModernMT/cli/mmt/engine.py", line 431, in __call__
    self._f(*args, **kwargs)
  File "/home/lm-dev8/MMT323/ModernMT/cli/mmt/engine.py", line 771, in _train_model
    n_train_steps=self._n_train_steps, n_eval_steps=self._n_eval_steps)
  File "/home/lm-dev8/MMT323/ModernMT/cli/mmt/engine.py", line 166, in train_model
    data_dir = os.path.join(train_dir, 'data')
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
It seems it uses a wrong way to build a data path.

**Comment by EtienneAb3d** [comment]
i did a second attempt, restarting from scratch, and I got the same result. 

I tried to provide options in a different order, without success.

I can resume with the "pack_model" option, but not without option, nor with the "train_model" option.

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

Thanks for having spotted this! I have just pushed a fix in the master branch.
