### ISSUE TITLE
Modern MT 3.3 does not train

### ISSUE THREAD

**Issue by LoekvanKooten** [modernmt/MMT#454]
Traceback (most recent call last):
  File "./mmt", line 610, in <module>
    main()
  File "./mmt", line 556, in main
    actions[command](args)
  File "./mmt", line 143, in main_create
    builder.build()
  File "/home/loek/.local/share/Trash/files/mmt8.2/cli/mmt/engine.py", line 556, in build
    self._build(resume=False)
  File "/home/loek/.local/share/Trash/files/mmt8.2/cli/mmt/engine.py", line 629, in _build
    method(self, args, skip=skip, log=log_stream, delete_on_exit=self._delete_on_exit)
  File "/home/loek/.local/share/Trash/files/mmt8.2/cli/mmt/engine.py", line 428, in __call__
    self._f(*args, **kwargs)
  File "/home/loek/.local/share/Trash/files/mmt8.2/cli/mmt/engine.py", line 768, in _train_model
    n_train_steps=self._n_train_steps, n_eval_steps=self._n_eval_steps)
  File "/home/loek/.local/share/Trash/files/mmt8.2/cli/mmt/engine.py", line 189, in train_model
    raise ShellError(' '.join(command), return_code, None)
cli.libs.osutils.ShellError: Command 't2t-trainer --t2t_usr_dir /home/loek/.local/share/Trash/files/mmt8.2/build/lib/t2t --data_dir=/home/loek/.local/share/Trash/files/mmt8.2/runtime/engjap/tmp/training/neural_train_data/data --problem=translate_mmt --model=transformer --hparams_set=transformer_base --output_dir=/home/loek/.local/share/Trash/files/mmt8.2/runtime/engjap/tmp/training/neural_model --local_eval_frequency=1000 --train_steps=100000000 --worker_gpu=1 --hparams batch_size=3072' failed with exit code 1

P.S. After several tries the error disappeared, but still it's strange that it takes so many tries.

**Comment by davidecaroselli** [comment]
We have just released a fixed version of ModernMT v3.3.1, can you please check if the problem still arises? Thanks!

**Comment by davidecaroselli** [comment]
Closing for now, if you still have such problems please don't hesitate to re-open it!
