### ISSUE TITLE
0.11.1 SNAPSHOT Fail to Run Example

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#46]
```
ubuntu@ip-172-30-0-162:~/mmt$ ./mmt create en it examples/data/train/

=========== TRAINING STARTED ===========

ENGINE:  default
CORPORA: /home/ubuntu/mmt/examples/data/train (3 documents)
LANGS:   en > it

INFO: (1 of 6) Corpora tokenization...                                 DONE (in 5s)
INFO: (2 of 6) Corpora cleaning...                                     DONE (in 0s)
INFO: (3 of 6) Context Analyzer training...                            DONE (in 0s)
INFO: (4 of 6) Language Model training...                              DONE (in 1s)
2016-01-14 23:49:40,164 [ERROR] - Command '/home/ubuntu/mmt/opt/bin/irstlm-adaptivelm-v0.6/bin/compile-lm /home/ubuntu/mmt/runtime/default/training/tmp/lm/arpa /home/ubuntu/mmt/engines/default/data/lm/europarl.alm' failed with exit code -6
Traceback (most recent call last):
  File "/home/ubuntu/mmt/scripts/engine.py", line 258, in build
    self._engine.lm.train(tokenized_corpora, self._engine.target_lang, working_dir, log_file)
  File "/home/ubuntu/mmt/scripts/mt/lm.py", line 118, in train
    self._train_lm(cfile, os.path.join(models_folder, lm), working_dir, log)
  File "/home/ubuntu/mmt/scripts/mt/lm.py", line 146, in _train_lm
    shell.execute(command, stderr=log)
  File "/home/ubuntu/mmt/scripts/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
ShellError: Command '/home/ubuntu/mmt/opt/bin/irstlm-adaptivelm-v0.6/bin/compile-lm /home/ubuntu/mmt/runtime/default/training/tmp/lm/arpa /home/ubuntu/mmt/engines/default/data/lm/europarl.alm' failed with exit code -6
Traceback (most recent call last):
  File "./mmt", line 387, in <module>
    main()
  File "./mmt", line 363, in main
    main_create(argv[1:])
  File "./mmt", line 346, in main_create
    engine.builder.build(corpora, debug=args.debug, steps=args.training_steps)
  File "/home/ubuntu/mmt/scripts/engine.py", line 258, in build
    self._engine.lm.train(tokenized_corpora, self._engine.target_lang, working_dir, log_file)
  File "/home/ubuntu/mmt/scripts/mt/lm.py", line 118, in train
    self._train_lm(cfile, os.path.join(models_folder, lm), working_dir, log)
  File "/home/ubuntu/mmt/scripts/mt/lm.py", line 146, in _train_lm
    shell.execute(command, stderr=log)
  File "/home/ubuntu/mmt/scripts/libs/shell.py", line 55, in execute
    raise ShellError(str_cmd, returncode, stderr_dump)
scripts.libs.shell.ShellError: Command '/home/ubuntu/mmt/opt/bin/irstlm-adaptivelm-v0.6/bin/compile-lm /home/ubuntu/mmt/runtime/default/training/tmp/lm/arpa /home/ubuntu/mmt/engines/default/data/lm/europarl.alm' failed with exit code -6
```

**Comment by davidecaroselli** [comment]
I run some tests, but unfortunately I could not replicate the bug. @marcotrombetti Could you please send me the log file under runtime/default/training/logs/lm.log ? Thanks!

**Comment by davidecaroselli** [comment]
I've found the problem: IRSTLM's compile-lm crashes with the arpa file created. It seems that the new scripts for unzipped LM training produce a malformed arpa file.
The command log says:

```
$ ./compile-lm arpa test.alm
inpfile: arpa
outfile: test.alm
loading up to the LM level 1000 (if any)
dub: 10000000
Segmentation fault (core dumped)

$ echo $?
139
```

You can find the file to reproduce the bug here: [arpa.zip](https://github.com/ModernMT/MMT/files/92298/arpa.zip)

compile-lm has been compiled from the last commit of irstlm, branch cd-correction-model.

**Comment by cattoni** [comment]
The "arpa" file is truncated: it contains only the 7217 unigrams and a subset of the 31432 bigrams (no 3-grams, 4-grams, 5-grams)

**Comment by davidecaroselli** [comment]
I suspect that this bug is related to the problems we're having with the new version of the LM training scripts wrote for issue #37

I'll keep you updated!

**Comment by mfederico** [comment]
The iarpa file looks broken. It ends with the bigram line
-3.311330	. Voteremo	-0.301030
-non

suspect the buildlm script crashed somewhere. 
Marcello

**Comment by marcotrombetti** [comment]
Few more notes after testing on 4 different hw.
Does not crashes on AWS with limited num cores <17.
I guess if a parallelization bug.

@davidecaroselli If you don't find the bug quickly consider rolling back. The LM change was minor (+10% training speed) and this releases add many important and critical fixes. (eg. broken tuning)

Marco
