### ISSUE TITLE
Cluster Start Error during Tuning

### ISSUE THREAD

**Issue by marcotrombetti** [ModernMT/MMT#62]
If I try to start a new node when a tuning is already running on the master I have this message:

```
./mmt start -e test --master-pem /home/ubuntu/My.pem --master ubuntu@52.23.215.71
```

```
tail -n 100 /home/ubuntu/mmt/runtime/test/slave/logs/process.log

org.zeromq.ZMQException: Errno 156384763 : Operation cannot be accomplished in current state
	at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:1456)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1306)
	at eu.modernmt.network.messaging.zeromq.ZMQMessagingClient$ClientLoop.request(ZMQMessagingClient.java:70)
	at eu.modernmt.network.messaging.zeromq.ZMQMessagingClient.request(ZMQMessagingClient.java:39)
	at eu.modernmt.network.cluster.Worker.internalSendRequest(Worker.java:80)
	at eu.modernmt.network.cluster.Worker.sendRequest(Worker.java:64)
	at eu.modernmt.engine.MMTWorker$Initializer.run(MMTWorker.java:157)
[Thread-1] INFO eu.modernmt.engine.MMTWorker - MMT Cluster Worker shutdown.
```

**Comment by davidecaroselli** [comment]
This has been solved by commit https://github.com/ModernMT/MMT/commit/08ce9b2e134fd1be33ce3cb18f33601dff99f65a.

I've tested this condition and now works as expected: the new node start translating and the results are correctly sent to master instance.
