### ISSUE TITLE
failure in case of empty input

### ISSUE THREAD

**Issue by nicolabertoldi** [ModernMT/MMT#88]
example: echo "" | ./extras/translate

Traceback (most recent call last):
  File "./extras/translate", line 234, in <module>
    exitcode = main()
  File "./extras/translate", line 208, in main
    executor.execute(line.strip())
  File "./extras/translate", line 139, in execute
    translation = self._translate(line)
  File "./extras/translate", line 68, in _translate
    return self.api.translate(line, session=self.session, processing=self.processing, nbest=self.nbest)
  File "/home/ubuntu/ModernMT/scripts/engine.py", line 521, in translate
    return self._get('translate', params=p)
  File "/home/ubuntu/ModernMT/scripts/engine.py", line 464, in _get
    return self._unpack(r)
  File "/home/ubuntu/ModernMT/scripts/engine.py", line 457, in _unpack
    raise Exception('HTTP request failed with code ' + str(r.status_code) + ': ' + r.url)
Exception: HTTP request failed with code 400: http://localhost:8045/translate?q=&processing=1

**Comment by nicolabertoldi** [comment]
The problem has been resolved in the branch empty_translation

@davidecaroselli   Could you please check if my solution is fine?  If yes, you can also merge into develop, and close the issue

**Comment by nicolabertoldi** [comment]
Still to decide the best heuristic for tags in case of empty input text
